; Sound Effects for song Sound effects, version 1.0, generated by Arkos Tracker 2.

; The sound effects, starting at 1.
	dw Soundeffects_Subsong_SoundEffect1	; Sound effect 1.
	dw Soundeffects_Subsong_SoundEffect2	; Sound effect 2.
	dw Soundeffects_Subsong_SoundEffect3	; Sound effect 3.
	dw Soundeffects_Subsong_SoundEffect4	; Sound effect 4.
	dw Soundeffects_Subsong_SoundEffect5	; Sound effect 5.

; Sound effect 1.
Soundeffects_Subsong_SoundEffect1
Soundeffects_Subsong_SoundEffect1_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 95	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 99	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 102	; Software period.

	db 173	; Soft only. Volume: 11.
	db 1	; Noise: 1.
	dw 106	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
Soundeffects_Subsong_SoundEffect2
Soundeffects_Subsong_SoundEffect2_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 301	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 301	; Software period.

	db 189	; Soft only. Volume: 15.
	db 8	; Noise: 8.
	dw 319	; Software period.

	db 189	; Soft only. Volume: 15.
	db 8	; Noise: 8.
	dw 319	; Software period.

	db 185	; Soft only. Volume: 14.
	db 2	; Noise: 2.
	dw 402	; Software period.

	db 185	; Soft only. Volume: 14.
	db 2	; Noise: 2.
	dw 402	; Software period.

	db 181	; Soft only. Volume: 13.
	db 16	; Noise: 16.
	dw 213	; Software period.

	db 181	; Soft only. Volume: 13.
	db 16	; Noise: 16.
	dw 213	; Software period.

	db 177	; Soft only. Volume: 12.
	db 2	; Noise: 2.
	dw 225	; Software period.

	db 177	; Soft only. Volume: 12.
	db 2	; Noise: 2.
	dw 225	; Software period.

	db 173	; Soft only. Volume: 11.
	db 2	; Noise: 2.
	dw 239	; Software period.

	db 173	; Soft only. Volume: 11.
	db 2	; Noise: 2.
	dw 239	; Software period.

	db 165	; Soft only. Volume: 9.
	db 16	; Noise: 16.
	dw 358	; Software period.

	db 165	; Soft only. Volume: 9.
	db 16	; Noise: 16.
	dw 358	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 119	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 119	; Software period.

	db 153	; Soft only. Volume: 6.
	db 7	; Noise: 7.
	dw 80	; Software period.

	db 4	; End of the sound effect.

; Sound effect 3.
Soundeffects_Subsong_SoundEffect3
Soundeffects_Subsong_SoundEffect3_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 119	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 119	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 60	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 60	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 95	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 95	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 47	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 47	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 80	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 80	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 40	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 40	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 478	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 30	; Hardware period.
	dw 956	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 30	; Hardware period.
	dw 956	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 30	; Hardware period.
	dw 956	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 30	; Hardware period.
	dw 956	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 239	; Software period.

	db 4	; End of the sound effect.

; Sound effect 4.
Soundeffects_Subsong_SoundEffect4
Soundeffects_Subsong_SoundEffect4_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 119	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 119	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 56	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 56	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 106	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 106	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 53	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 53	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 100	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 100	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 50	; Software period.

	db 4	; End of the sound effect.

; Sound effect 5.
Soundeffects_Subsong_SoundEffect5
Soundeffects_Subsong_SoundEffect5_Loop	db 3	; Soft and Hard. Env: 8.
	dw 2	; Hardware period.
	dw 27	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 2	; Hardware period.
	dw 27	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 3	; Hardware period.
	dw 47	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 3	; Hardware period.
	dw 47	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 2	; Hardware period.
	dw 30	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 2	; Hardware period.
	dw 30	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 5	; Hardware period.
	dw 75	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 5	; Hardware period.
	dw 75	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 3	; Hardware period.
	dw 47	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 3	; Hardware period.
	dw 47	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 5	; Hardware period.
	dw 75	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 5	; Hardware period.
	dw 75	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 12	; Hardware period.
	dw 190	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 12	; Hardware period.
	dw 190	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 7	; Hardware period.
	dw 119	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 19	; Hardware period.
	dw 301	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 19	; Hardware period.
	dw 301	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 12	; Hardware period.
	dw 190	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 12	; Hardware period.
	dw 190	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 34	; Hardware period.
	dw 536	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 34	; Hardware period.
	dw 536	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 50	; Hardware period.
	dw 804	; Software period.

	db 4	; End of the sound effect.

