; Song Just add cream, in AKY version 1.0, generated by Arkos Tracker 2.

Main_Subsong0:

; Header
	dc.b 128	; Format version: 0 and endianness: little-endian.
	dc.b 3	; How many channels are encoded.
; Frequency of the PSG index 0: 2000000Hz.
	dc.b 128, 132, 30, 0

Main_Subsong0_Linker:
; Pattern 0
Main_Subsong0_LinkerLoop:	; Loops here.
	dc.w 384	; Duration in frames.
	dc.w Main_Subsong0_Track_12-Main_Subsong0
	dc.w Main_Subsong0_Track_13-Main_Subsong0
	dc.w Main_Subsong0_Track_2-Main_Subsong0

; Pattern 1
	dc.w 384	; Duration in frames.
	dc.w Main_Subsong0_Track_12-Main_Subsong0
	dc.w Main_Subsong0_Track_13-Main_Subsong0
	dc.w Main_Subsong0_Track_5-Main_Subsong0

; Pattern 2
	dc.w 384	; Duration in frames.
	dc.w Main_Subsong0_Track_9-Main_Subsong0
	dc.w Main_Subsong0_Track_14-Main_Subsong0
	dc.w Main_Subsong0_Track_14-Main_Subsong0

; Pattern 3
	dc.w 384	; Duration in frames.
	dc.w Main_Subsong0_Track_9-Main_Subsong0
	dc.w Main_Subsong0_Track_13-Main_Subsong0
	dc.w Main_Subsong0_Track_14-Main_Subsong0

; Pattern 4
	dc.w 384	; Duration in frames.
	dc.w Main_Subsong0_Track_12-Main_Subsong0
	dc.w Main_Subsong0_Track_13-Main_Subsong0
	dc.w Main_Subsong0_Track_14-Main_Subsong0

	dc.w 0	; Loops (duration = 0).
	dc.w Main_Subsong0_LinkerLoop-Main_Subsong0

; The tracks.
Main_Subsong0_Track_2:
	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_2-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_3-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_4-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_2-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_7-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_2-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_9-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_10-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_11-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_12-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_13-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_14-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_15-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_16-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_17-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_19-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_24-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_26-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_24-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_25-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_26-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_27-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_28-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_29-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_31-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_28-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_33-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_31-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_28-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_33-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_39-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_40-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_33-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_42-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_43-Main_Subsong0

	dc.b 24	; Duration.
	dc.w Main_Subsong0_RegisterBlock_44-Main_Subsong0

	dc.b 72	; Duration.
	dc.w Main_Subsong0_RegisterBlock_45-Main_Subsong0

Main_Subsong0_Track_5:
	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_2-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_3-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_4-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_2-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_7-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_2-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_9-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_10-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_11-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_12-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_13-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_14-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_15-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_16-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_17-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_19-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_24-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_26-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_24-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_25-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_26-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_27-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_28-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_29-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_31-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_28-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_33-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_31-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_28-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_33-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_85-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_86-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_87-Main_Subsong0

	dc.b 19	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_89-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_7-Main_Subsong0

	dc.b 17	; Duration.
	dc.w Main_Subsong0_RegisterBlock_91-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_92-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_93-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_94-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_95-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_96-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_85-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_98-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_87-Main_Subsong0

Main_Subsong0_Track_9:
	dc.b 19	; Duration.
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_104-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_134-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_132-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0

	dc.b 19	; Duration.
	dc.w Main_Subsong0_RegisterBlock_112-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_114-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_112-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_112-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_132-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_112-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_120-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 19	; Duration.
	dc.w Main_Subsong0_RegisterBlock_122-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_124-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_122-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_122-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_132-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_122-Main_Subsong0

	dc.b 19	; Duration.
	dc.w Main_Subsong0_RegisterBlock_130-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_132-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_134-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_132-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_130-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_134-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_139-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_112-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_139-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_134-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

Main_Subsong0_Track_12:
	dc.b 19	; Duration.
	dc.w Main_Subsong0_RegisterBlock_146-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_148-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_134-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_146-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_132-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_155-Main_Subsong0

	dc.b 19	; Duration.
	dc.w Main_Subsong0_RegisterBlock_156-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_158-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_160-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_112-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_132-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_156-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_120-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_165-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_166-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_166-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_124-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_171-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_122-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_132-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_166-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_130-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_165-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_177-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_134-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_181-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_130-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_134-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_184-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_156-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_187-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_134-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

Main_Subsong0_Track_13:
	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_191-Main_Subsong0

	dc.b 17	; Duration.
	dc.w Main_Subsong0_RegisterBlock_192-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_193-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_194-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_193-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_194-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_197-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_198-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_199-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_198-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_193-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_202-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_198-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_204-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_198-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_204-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_226-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_193-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_198-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_199-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_198-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_193-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_202-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_198-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_193-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_202-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_198-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_218-Main_Subsong0

	dc.b 17	; Duration.
	dc.w Main_Subsong0_RegisterBlock_219-Main_Subsong0

	dc.b 24	; Duration.
	dc.w Main_Subsong0_RegisterBlock_220-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_223-Main_Subsong0

	dc.b 17	; Duration.
	dc.w Main_Subsong0_RegisterBlock_222-Main_Subsong0

	dc.b 24	; Duration.
	dc.w Main_Subsong0_RegisterBlock_223-Main_Subsong0

	dc.b 7	; Duration.
	dc.w Main_Subsong0_RegisterBlock_193-Main_Subsong0

	dc.b 5	; Duration.
	dc.w Main_Subsong0_RegisterBlock_202-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_226-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_197-Main_Subsong0

Main_Subsong0_Track_14:
	dc.b 255	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0

	dc.b 129	; Duration.
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0


; The RegisterBlocks.
Main_Subsong0_RegisterBlock_229:
	dc.b 0	; Initial State: no software, no hardware.

Main_Subsong0_RegisterBlock_229_Loop:
	dc.b 4	; Non-initial State, no software no hardware.

	dc.b 8	; Loop to index 1.
	dc.w Main_Subsong0_RegisterBlock_229_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_45:
	dc.b 81	; Initial State: software only.
	dc.b 224, 1	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 219	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 219	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 219	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 219	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 219	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 219	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 219	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 219	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.


Main_Subsong0_RegisterBlock_44:
	dc.b 89	; Initial State: software only.
	dc.b 229, 1	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 227	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 109	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

Main_Subsong0_RegisterBlock_44_Loop:
	dc.b 45	; Non-initial State, software only.

	dc.b 109	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 224	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 219	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 221	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 8	; Loop to index 6.
	dc.w Main_Subsong0_RegisterBlock_44_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_220:
	dc.b 97	; Initial State: software only.
	dc.b 142, 0	; Software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_220_Loop:
	dc.b 101	; Non-initial State, software only.
	dc.b 142	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 8	; Loop to index 6.
	dc.w Main_Subsong0_RegisterBlock_220_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_223:
	dc.b 97	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_223_Loop:
	dc.b 101	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 8	; Loop to index 6.
	dc.w Main_Subsong0_RegisterBlock_223_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_88:
	dc.b 113	; Initial State: software only.
	dc.b 62, 1	; Software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 60	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 62	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 64	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 66	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 62	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 60	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 62	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 64	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 66	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 62	; New LSB for software period.


Main_Subsong0_RegisterBlock_102:
	dc.b 131	; Initial State : software and hardware.
	dc.b 225, 8	; Software period.
	dc.b 71, 0	; Hardware period.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 53	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_102_Loop:
	dc.b 45	; Non-initial State, software only.

	dc.b 8	; Loop to index 4.
	dc.w Main_Subsong0_RegisterBlock_102_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_112:
	dc.b 131	; Initial State : software and hardware.
	dc.b 167, 6	; Software period.
	dc.b 53, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_122:
	dc.b 131	; Initial State : software and hardware.
	dc.b 152, 5	; Software period.
	dc.b 45, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_130:
	dc.b 131	; Initial State : software and hardware.
	dc.b 252, 4	; Software period.
	dc.b 40, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_146:
	dc.b 109	; Initial State: software only.
	dc.b 31	; Noise.
	dc.b 188, 3	; Software period.

	dc.b 125	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 253	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 253	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_146_Loop:
	dc.b 237	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.
	dc.b 8	; New MSB for software period, maybe with noise.

	dc.b 8	; Loop to index 4.
	dc.w Main_Subsong0_RegisterBlock_146_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_156:
	dc.b 109	; Initial State: software only.
	dc.b 31	; Noise.
	dc.b 188, 3	; Software period.

	dc.b 125	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 253	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 253	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_156_Loop:
	dc.b 237	; Non-initial State, software only.
	dc.b 167	; New LSB for software period.
	dc.b 6	; New MSB for software period, maybe with noise.

	dc.b 8	; Loop to index 4.
	dc.w Main_Subsong0_RegisterBlock_156_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_91:
	dc.b 65	; Initial State: software only.
	dc.b 62, 1	; Software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 60	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 62	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 64	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 66	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 62	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 60	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 62	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 64	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 66	; New LSB for software period.


Main_Subsong0_RegisterBlock_192:
	dc.b 65	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 21	; Non-initial State, software only.

	dc.b 85	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 21	; Non-initial State, software only.

	dc.b 85	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 17	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_219:
	dc.b 65	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 213	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 213	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 21	; Non-initial State, software only.

	dc.b 85	; Non-initial State, software only.
	dc.b 213	; New LSB for software period.

	dc.b 21	; Non-initial State, software only.

	dc.b 85	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 17	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_222:
	dc.b 65	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 21	; Non-initial State, software only.

	dc.b 85	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 21	; Non-initial State, software only.

	dc.b 85	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 17	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_4:
	dc.b 113	; Initial State: software only.
	dc.b 213, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 6	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_7:
	dc.b 113	; Initial State: software only.
	dc.b 239, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 6	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_14:
	dc.b 89	; Initial State: software only.
	dc.b 238, 0	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 236	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 238	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 240	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 242	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 238	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 236	; New LSB for software period.


Main_Subsong0_RegisterBlock_19:
	dc.b 41	; Initial State: software only.
	dc.b 218, 0	; Software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 228	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 233	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 238	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 243	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 197	; Non-initial State, software only.
	dc.b 2	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 69	; Non-initial State, software only.
	dc.b 7	; New LSB for software period.

	dc.b 69	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.

	dc.b 65	; Non-initial State, software only.
	dc.b 17	; New LSB for software period.


Main_Subsong0_RegisterBlock_86:
	dc.b 89	; Initial State: software only.
	dc.b 60, 1	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 57	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 54	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 51	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 48	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 45	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 42	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 39	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 33	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 30	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.


Main_Subsong0_RegisterBlock_94:
	dc.b 89	; Initial State: software only.
	dc.b 252, 0	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 254	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 0	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 237	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 109	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.


Main_Subsong0_RegisterBlock_120:
	dc.b 131	; Initial State : software and hardware.
	dc.b 237, 5	; Software period.
	dc.b 47, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_121:
	dc.b 0	; Initial State: no software, no hardware.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0 + 1	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_132:
	dc.b 131	; Initial State : software and hardware.
	dc.b 119, 7	; Software period.
	dc.b 60, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_139:
	dc.b 131	; Initial State : software and hardware.
	dc.b 233, 7	; Software period.
	dc.b 63, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_155:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_146-Main_Subsong0 + 12	; Optimization: goto common Block at index 4.

Main_Subsong0_RegisterBlock_160:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_156-Main_Subsong0 + 12	; Optimization: goto common Block at index 4.

Main_Subsong0_RegisterBlock_165:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0 + 1	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_166:
	dc.b 109	; Initial State: software only.
	dc.b 31	; Noise.
	dc.b 188, 3	; Software period.

	dc.b 125	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 253	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 253	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_166_Loop:
	dc.b 109	; Non-initial State, software only.
	dc.b 152	; New LSB for software period.

	dc.b 8	; Loop to index 4.
	dc.w Main_Subsong0_RegisterBlock_166_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_171:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

Main_Subsong0_RegisterBlock_171_Loop:
	dc.b 237	; Non-initial State, software only.
	dc.b 152	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 8	; Loop to index 5.
	dc.w Main_Subsong0_RegisterBlock_171_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_177:
	dc.b 109	; Initial State: software only.
	dc.b 31	; Noise.
	dc.b 188, 3	; Software period.

	dc.b 125	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 253	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 253	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_177_Loop:
	dc.b 237	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.
	dc.b 7	; New MSB for software period, maybe with noise.

	dc.b 8	; Loop to index 4.
	dc.w Main_Subsong0_RegisterBlock_177_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_181:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_177-Main_Subsong0 + 12	; Optimization: goto common Block at index 4.

Main_Subsong0_RegisterBlock_184:
	dc.b 109	; Initial State: software only.
	dc.b 31	; Noise.
	dc.b 188, 3	; Software period.

	dc.b 125	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 253	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 253	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_184_Loop:
	dc.b 237	; Non-initial State, software only.
	dc.b 233	; New LSB for software period.
	dc.b 7	; New MSB for software period, maybe with noise.

	dc.b 8	; Loop to index 4.
	dc.w Main_Subsong0_RegisterBlock_184_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_187:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_184-Main_Subsong0 + 12	; Optimization: goto common Block at index 4.

Main_Subsong0_RegisterBlock_193:
	dc.b 97	; Initial State: software only.
	dc.b 190, 0	; Software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_194:
	dc.b 89	; Initial State: software only.
	dc.b 213, 0	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 213	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 217	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 25	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_197:
	dc.b 89	; Initial State: software only.
	dc.b 239, 0	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 217	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_198:
	dc.b 97	; Initial State: software only.
	dc.b 179, 0	; Software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_204:
	dc.b 89	; Initial State: software only.
	dc.b 190, 0	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_194-Main_Subsong0 + 17	; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_226:
	dc.b 97	; Initial State: software only.
	dc.b 213, 0	; Software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 213	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_193-Main_Subsong0 + 6	; Optimization: goto common Block at index 3.

Main_Subsong0_RegisterBlock_0:
	dc.b 113	; Initial State: software only.
	dc.b 200, 0	; Software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 199	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 198	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 197	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 196	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 194	; New LSB for software period.


Main_Subsong0_RegisterBlock_2:
	dc.b 105	; Initial State: software only.
	dc.b 28, 1	; Software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 25	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_10:
	dc.b 105	; Initial State: software only.
	dc.b 239, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_2-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_12:
	dc.b 113	; Initial State: software only.
	dc.b 251, 0	; Software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 245	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 243	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.


Main_Subsong0_RegisterBlock_15:
	dc.b 105	; Initial State: software only.
	dc.b 213, 0	; Software period.

	dc.b 49	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_17:
	dc.b 65	; Initial State: software only.
	dc.b 238, 0	; Software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 236	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 238	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 240	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.


Main_Subsong0_RegisterBlock_20:
	dc.b 105	; Initial State: software only.
	dc.b 123, 1	; Software period.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_22:
	dc.b 65	; Initial State: software only.
	dc.b 213, 0	; Software period.

Main_Subsong0_RegisterBlock_22_Loop:
	dc.b 33	; Non-initial State, software only.

	dc.b 8	; Loop to index 1.
	dc.w Main_Subsong0_RegisterBlock_22_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_24:
	dc.b 105	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_26:
	dc.b 57	; Initial State: software only.
	dc.b 123, 1	; Software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 25	; Non-initial State, software only.

	dc.b 25	; Non-initial State, software only.

	dc.b 25	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_28:
	dc.b 113	; Initial State: software only.
	dc.b 101, 1	; Software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 99	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 101	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 103	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.


Main_Subsong0_RegisterBlock_30:
	dc.b 105	; Initial State: software only.
	dc.b 123, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_15-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_40:
	dc.b 105	; Initial State: software only.
	dc.b 222, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_42:
	dc.b 113	; Initial State: software only.
	dc.b 248, 1	; Software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 245	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 242	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.


Main_Subsong0_RegisterBlock_85:
	dc.b 113	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 6	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_92:
	dc.b 113	; Initial State: software only.
	dc.b 10, 1	; Software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 9	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 7	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 6	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 4	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 3	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 1	; New LSB for software period.


Main_Subsong0_RegisterBlock_95:
	dc.b 105	; Initial State: software only.
	dc.b 28, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_15-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_104:
	dc.b 131	; Initial State : software and hardware.
	dc.b 112, 4	; Software period.
	dc.b 36, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_109:
	dc.b 131	; Initial State : software and hardware.
	dc.b 119, 7	; Software period.
	dc.b 60, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_114:
	dc.b 131	; Initial State : software and hardware.
	dc.b 77, 13	; Software period.
	dc.b 106, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_124:
	dc.b 131	; Initial State : software and hardware.
	dc.b 47, 11	; Software period.
	dc.b 89, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_134:
	dc.b 131	; Initial State : software and hardware.
	dc.b 247, 9	; Software period.
	dc.b 80, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_148:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 237	; Non-initial State, software only.
	dc.b 112	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_158:
	dc.b 109	; Initial State: software only.
	dc.b 31	; Noise.
	dc.b 188, 3	; Software period.

	dc.b 125	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 253	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 253	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 237	; Non-initial State, software only.
	dc.b 77	; New LSB for software period.
	dc.b 13	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_191:
	dc.b 97	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.


Main_Subsong0_RegisterBlock_199:
	dc.b 65	; Initial State: software only.
	dc.b 179, 0	; Software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.


Main_Subsong0_RegisterBlock_207:
	dc.b 97	; Initial State: software only.
	dc.b 213, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_226-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_218:
	dc.b 97	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 213	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.


Main_Subsong0_RegisterBlock_221:
	dc.b 97	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_223-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_1:
	dc.b 89	; Initial State: software only.
	dc.b 193, 0	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 192	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 191	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_3:
	dc.b 65	; Initial State: software only.
	dc.b 190, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_6:
	dc.b 65	; Initial State: software only.
	dc.b 213, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_9:
	dc.b 65	; Initial State: software only.
	dc.b 239, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_11:
	dc.b 57	; Initial State: software only.
	dc.b 28, 1	; Software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 25	; Non-initial State, software only.

	dc.b 21	; Non-initial State, software only.

	dc.b 17	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_13:
	dc.b 89	; Initial State: software only.
	dc.b 239, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 8	; Optimization: goto common Block at index 4.

Main_Subsong0_RegisterBlock_16:
	dc.b 57	; Initial State: software only.
	dc.b 218, 0	; Software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 223	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 228	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 233	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 238	; New LSB for software period.


Main_Subsong0_RegisterBlock_18:
	dc.b 57	; Initial State: software only.
	dc.b 213, 0	; Software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_11-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_21:
	dc.b 105	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_23:
	dc.b 57	; Initial State: software only.
	dc.b 123, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_26-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_25:
	dc.b 105	; Initial State: software only.
	dc.b 28, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_27:
	dc.b 57	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_26-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_29:
	dc.b 57	; Initial State: software only.
	dc.b 27, 1	; Software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 26	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 25	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 26	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 27	; New LSB for software period.


Main_Subsong0_RegisterBlock_31:
	dc.b 65	; Initial State: software only.
	dc.b 101, 1	; Software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 99	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 101	; New LSB for software period.


Main_Subsong0_RegisterBlock_33:
	dc.b 57	; Initial State: software only.
	dc.b 123, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_39:
	dc.b 65	; Initial State: software only.
	dc.b 102, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_43:
	dc.b 89	; Initial State: software only.
	dc.b 238, 1	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 236	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 235	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 233	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 232	; New LSB for software period.


Main_Subsong0_RegisterBlock_87:
	dc.b 65	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_89:
	dc.b 65	; Initial State: software only.
	dc.b 27, 1	; Software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 26	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 25	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 26	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 27	; New LSB for software period.


Main_Subsong0_RegisterBlock_93:
	dc.b 89	; Initial State: software only.
	dc.b 0, 1	; Software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 254	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 109	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_96:
	dc.b 65	; Initial State: software only.
	dc.b 252, 0	; Software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.


Main_Subsong0_RegisterBlock_98:
	dc.b 57	; Initial State: software only.
	dc.b 28, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_103:
	dc.b 0	; Initial State: no software, no hardware.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_229-Main_Subsong0 + 1	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_107:
	dc.b 131	; Initial State : software and hardware.
	dc.b 247, 9	; Software period.
	dc.b 80, 0	; Hardware period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 5	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_202:
	dc.b 65	; Initial State: software only.
	dc.b 190, 0	; Software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.


