; Events generated by Arkos Tracker 3.

    ;org 0

Events:
EventsDisarkGenerateExternalLabel:

DisarkByteRegionStart0:
Events_Loop:
    dc.w 11473    ; Wait for 11472 frames.
    dc.w 0

    dc.w 0    ; End of sequence.
DisarkWordForceReference1:
    dc.l Events_Loop    ; Loops here.
DisarkByteRegionEnd0:
