; Song Canon in D major, in AKY version 1.0, generated by Arkos Tracker 2.

Main_Subsong0:

; Header
	dc.b 128	; Format version: 0 and endianness: little-endian.
	dc.b 3	; How many channels are encoded.
; Frequency of the PSG index 0: 2000000Hz.
	dc.b 128, 132, 30, 0

Main_Subsong0_Linker:
; Pattern 0
	dc.w 320	; Duration in frames.
	dc.w Main_Subsong0_Track_18-Main_Subsong0
	dc.w Main_Subsong0_Track_19-Main_Subsong0
	dc.w Main_Subsong0_Track_5-Main_Subsong0

; Pattern 1
	dc.w 320	; Duration in frames.
	dc.w Main_Subsong0_Track_21-Main_Subsong0
	dc.w Main_Subsong0_Track_22-Main_Subsong0
	dc.w Main_Subsong0_Track_5-Main_Subsong0

; Pattern 2
Main_Subsong0_LinkerLoop:	; Loops here.
	dc.w 320	; Duration in frames.
	dc.w Main_Subsong0_Track_18-Main_Subsong0
	dc.w Main_Subsong0_Track_19-Main_Subsong0
	dc.w Main_Subsong0_Track_13-Main_Subsong0

; Pattern 3
	dc.w 320	; Duration in frames.
	dc.w Main_Subsong0_Track_21-Main_Subsong0
	dc.w Main_Subsong0_Track_22-Main_Subsong0
	dc.w Main_Subsong0_Track_16-Main_Subsong0

; Pattern 4
	dc.w 320	; Duration in frames.
	dc.w Main_Subsong0_Track_19-Main_Subsong0
	dc.w Main_Subsong0_Track_13-Main_Subsong0
	dc.w Main_Subsong0_Track_20-Main_Subsong0

; Pattern 5
	dc.w 320	; Duration in frames.
	dc.w Main_Subsong0_Track_22-Main_Subsong0
	dc.w Main_Subsong0_Track_16-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0

; Pattern 6
	dc.w 320	; Duration in frames.
	dc.w Main_Subsong0_Track_18-Main_Subsong0
	dc.w Main_Subsong0_Track_19-Main_Subsong0
	dc.w Main_Subsong0_Track_20-Main_Subsong0

; Pattern 7
	dc.w 320	; Duration in frames.
	dc.w Main_Subsong0_Track_21-Main_Subsong0
	dc.w Main_Subsong0_Track_22-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0

	dc.w 0	; Loops (duration = 0).
	dc.w Main_Subsong0_LinkerLoop-Main_Subsong0

; The tracks.
Main_Subsong0_Track_5:
	dc.b 255	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 65	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

Main_Subsong0_Track_13:
	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_3-Main_Subsong0

	dc.b 30	; Duration.
	dc.w Main_Subsong0_RegisterBlock_4-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_5-Main_Subsong0

	dc.b 30	; Duration.
	dc.w Main_Subsong0_RegisterBlock_6-Main_Subsong0

	dc.b 40	; Duration.
	dc.w Main_Subsong0_RegisterBlock_7-Main_Subsong0

	dc.b 40	; Duration.
	dc.w Main_Subsong0_RegisterBlock_8-Main_Subsong0

	dc.b 40	; Duration.
	dc.w Main_Subsong0_RegisterBlock_9-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_10-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_11-Main_Subsong0

	dc.b 20	; Duration.
	dc.w Main_Subsong0_RegisterBlock_12-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_13-Main_Subsong0

	dc.b 30	; Duration.
	dc.w Main_Subsong0_RegisterBlock_14-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_15-Main_Subsong0

	dc.b 30	; Duration.
	dc.w Main_Subsong0_RegisterBlock_16-Main_Subsong0

Main_Subsong0_Track_16:
	dc.b 40	; Duration.
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0

	dc.b 40	; Duration.
	dc.w Main_Subsong0_RegisterBlock_19-Main_Subsong0

	dc.b 40	; Duration.
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0

	dc.b 20	; Duration.
	dc.w Main_Subsong0_RegisterBlock_21-Main_Subsong0

	dc.b 20	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_23-Main_Subsong0

	dc.b 20	; Duration.
	dc.w Main_Subsong0_RegisterBlock_24-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_25-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_26-Main_Subsong0

	dc.b 30	; Duration.
	dc.w Main_Subsong0_RegisterBlock_27-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_28-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_29-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_29-Main_Subsong0

	dc.b 20	; Duration.
	dc.w Main_Subsong0_RegisterBlock_32-Main_Subsong0

	dc.b 20	; Duration.
	dc.w Main_Subsong0_RegisterBlock_33-Main_Subsong0

Main_Subsong0_Track_18:
	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_35-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_36-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_37-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_38-Main_Subsong0

Main_Subsong0_Track_19:
	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_40-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_41-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_42-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_43-Main_Subsong0

Main_Subsong0_Track_20:
	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_45-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_46-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_47-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_45-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_46-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_47-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_45-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_54-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_105-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_56-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_57-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_58-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_59-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_61-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_59-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_63-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_64-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_61-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_59-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_47-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_45-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_70-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_45-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_47-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_45-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_59-Main_Subsong0

Main_Subsong0_Track_21:
	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_78-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_79-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_78-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_36-Main_Subsong0

Main_Subsong0_Track_22:
	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_83-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_40-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_83-Main_Subsong0

	dc.b 80	; Duration.
	dc.w Main_Subsong0_RegisterBlock_41-Main_Subsong0

Main_Subsong0_Track_23:
	dc.b 20	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_70-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_90-Main_Subsong0

	dc.b 20	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_47-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_64-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_61-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_64-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_63-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_64-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_61-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_90-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_101-Main_Subsong0

	dc.b 20	; Duration.
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_105-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_54-Main_Subsong0

	dc.b 20	; Duration.
	dc.w Main_Subsong0_RegisterBlock_105-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_106-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_63-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_54-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_105-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_110-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_57-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_112-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_59-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 10	; Duration.
	dc.w Main_Subsong0_RegisterBlock_47-Main_Subsong0


; The RegisterBlocks.
Main_Subsong0_RegisterBlock_0:
	dc.b 0	; Initial State: no software, no hardware.

Main_Subsong0_RegisterBlock_0_Loop:
	dc.b 4	; Non-initial State, no software no hardware.

	dc.b 8	; Loop to index 1.
	dc.w Main_Subsong0_RegisterBlock_0_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_35:
	dc.b 81	; Initial State: software only.
	dc.b 83, 3	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 81	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 80	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 79	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 80	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 81	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_35_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 83	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 85	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 86	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 87	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 86	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 85	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 83	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 81	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 80	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 79	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 80	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 81	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 32.
	dc.w Main_Subsong0_RegisterBlock_35_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_36:
	dc.b 81	; Initial State: software only.
	dc.b 112, 4	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 110	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 109	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 108	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 109	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 110	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_36_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 112	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 114	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 115	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 116	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 115	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 114	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 112	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 110	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 109	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 108	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 109	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 110	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 32.
	dc.w Main_Subsong0_RegisterBlock_36_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_37:
	dc.b 81	; Initial State: software only.
	dc.b 244, 3	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 242	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 240	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 242	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_37_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 246	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 246	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 242	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 240	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 242	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 32.
	dc.w Main_Subsong0_RegisterBlock_37_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_38:
	dc.b 81	; Initial State: software only.
	dc.b 71, 5	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 69	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 68	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 67	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 68	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 69	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_38_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 71	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 73	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 74	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 75	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 74	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 73	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 71	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 69	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 68	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 67	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 68	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 69	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 32.
	dc.w Main_Subsong0_RegisterBlock_38_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_40:
	dc.b 65	; Initial State: software only.
	dc.b 82, 1	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_40_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 8.
	dc.w Main_Subsong0_RegisterBlock_40_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_41:
	dc.b 65	; Initial State: software only.
	dc.b 123, 1	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_41_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 8.
	dc.w Main_Subsong0_RegisterBlock_41_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_42:
	dc.b 65	; Initial State: software only.
	dc.b 82, 1	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_42_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 8.
	dc.w Main_Subsong0_RegisterBlock_42_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_43:
	dc.b 65	; Initial State: software only.
	dc.b 82, 1	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_43_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 8.
	dc.w Main_Subsong0_RegisterBlock_43_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_78:
	dc.b 81	; Initial State: software only.
	dc.b 252, 4	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_78_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 254	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 0	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 254	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 32.
	dc.w Main_Subsong0_RegisterBlock_78_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_79:
	dc.b 81	; Initial State: software only.
	dc.b 167, 6	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 165	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 164	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 163	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 164	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 165	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_79_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 167	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 169	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 171	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 169	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 167	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 165	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 164	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 163	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 164	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 165	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 32.
	dc.w Main_Subsong0_RegisterBlock_79_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_83:
	dc.b 65	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_83_Loop:
	dc.b 93	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 8	; Loop to index 8.
	dc.w Main_Subsong0_RegisterBlock_83_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_7:
	dc.b 89	; Initial State: software only.
	dc.b 122, 1	; Software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 120	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 120	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

Main_Subsong0_RegisterBlock_7_Loop:
	dc.b 105	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 120	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 8	; Loop to index 18.
	dc.w Main_Subsong0_RegisterBlock_7_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_8:
	dc.b 73	; Initial State: software only.
	dc.b 125, 1	; Software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 120	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 120	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 120	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 125	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 124	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 122	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 121	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 120	; New LSB for software period.


Main_Subsong0_RegisterBlock_9:
	dc.b 89	; Initial State: software only.
	dc.b 170, 1	; Software period.

	dc.b 49	; Non-initial State, software only.

	dc.b 53	; Non-initial State, software only.

	dc.b 53	; Non-initial State, software only.

	dc.b 53	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_9_Loop:
	dc.b 41	; Non-initial State, software only.

	dc.b 8	; Loop to index 9.
	dc.w Main_Subsong0_RegisterBlock_9_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_18:
	dc.b 89	; Initial State: software only.
	dc.b 249, 1	; Software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

Main_Subsong0_RegisterBlock_18_Loop:
	dc.b 105	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 8	; Loop to index 18.
	dc.w Main_Subsong0_RegisterBlock_18_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_19:
	dc.b 73	; Initial State: software only.
	dc.b 252, 1	; Software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.


Main_Subsong0_RegisterBlock_20:
	dc.b 89	; Initial State: software only.
	dc.b 56, 2	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_9-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_4:
	dc.b 81	; Initial State: software only.
	dc.b 92, 1	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 91	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 89	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 88	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 87	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 86	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 85	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 84	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 83	; New LSB for software period.

Main_Subsong0_RegisterBlock_4_Loop:
	dc.b 105	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.

	dc.b 8	; Loop to index 11.
	dc.w Main_Subsong0_RegisterBlock_4_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_6:
	dc.b 73	; Initial State: software only.
	dc.b 82, 1	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 83	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 84	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 85	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 86	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 87	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 88	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 89	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 91	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 92	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 93	; New LSB for software period.


Main_Subsong0_RegisterBlock_14:
	dc.b 73	; Initial State: software only.
	dc.b 211, 1	; Software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 210	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 209	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 208	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 207	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 206	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 205	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 203	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 202	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 200	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 199	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 198	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 197	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 196	; New LSB for software period.

Main_Subsong0_RegisterBlock_14_Loop:
	dc.b 101	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.

	dc.b 8	; Loop to index 17.
	dc.w Main_Subsong0_RegisterBlock_14_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_16:
	dc.b 65	; Initial State: software only.
	dc.b 195, 1	; Software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 196	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 197	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 198	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 199	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 200	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 202	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 203	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 205	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 206	; New LSB for software period.


Main_Subsong0_RegisterBlock_27:
	dc.b 81	; Initial State: software only.
	dc.b 249, 1	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 248	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

Main_Subsong0_RegisterBlock_27_Loop:
	dc.b 105	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0 + 19	; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_12:
	dc.b 73	; Initial State: software only.
	dc.b 170, 1	; Software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 171	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 172	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 173	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 174	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 175	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 176	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 177	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 178	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 180	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 181	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 182	; New LSB for software period.


Main_Subsong0_RegisterBlock_21:
	dc.b 73	; Initial State: software only.
	dc.b 56, 2	; Software period.

Main_Subsong0_RegisterBlock_21_Loop:
	dc.b 37	; Non-initial State, software only.

	dc.b 8	; Loop to index 1.
	dc.w Main_Subsong0_RegisterBlock_21_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_22:
	dc.b 73	; Initial State: software only.
	dc.b 57, 2	; Software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 58	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 59	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 60	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 62	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 64	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 66	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 67	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 68	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 69	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 70	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 71	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 72	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 73	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 74	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 75	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 76	; New LSB for software period.


Main_Subsong0_RegisterBlock_24:
	dc.b 81	; Initial State: software only.
	dc.b 2, 2	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 0	; New LSB for software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 254	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 105	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

Main_Subsong0_RegisterBlock_24_Loop:
	dc.b 105	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 8	; Loop to index 4.
	dc.w Main_Subsong0_RegisterBlock_24_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_32:
	dc.b 81	; Initial State: software only.
	dc.b 194, 1	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 193	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 192	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 193	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 194	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 196	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 197	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 198	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 197	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 196	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 194	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 193	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 192	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 193	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 194	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 196	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 197	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 198	; New LSB for software period.


Main_Subsong0_RegisterBlock_33:
	dc.b 81	; Initial State: software only.
	dc.b 170, 1	; Software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_33_Loop:
	dc.b 33	; Non-initial State, software only.

	dc.b 8	; Loop to index 9.
	dc.w Main_Subsong0_RegisterBlock_33_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_88:
	dc.b 81	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_21-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_102:
	dc.b 73	; Initial State: software only.
	dc.b 253, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_33-Main_Subsong0 + 6	; Optimization: goto common Block at index 4.

Main_Subsong0_RegisterBlock_105:
	dc.b 81	; Initial State: software only.
	dc.b 253, 0	; Software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0 + 6	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_3:
	dc.b 89	; Initial State: software only.
	dc.b 101, 1	; Software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 99	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 98	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 97	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 96	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 95	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 109	; Non-initial State, software only.
	dc.b 94	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 93	; New LSB for software period.


Main_Subsong0_RegisterBlock_5:
	dc.b 73	; Initial State: software only.
	dc.b 82, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_21-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_10:
	dc.b 81	; Initial State: software only.
	dc.b 169, 1	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 168	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 167	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 168	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 169	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 171	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 172	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 173	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 172	; New LSB for software period.


Main_Subsong0_RegisterBlock_11:
	dc.b 73	; Initial State: software only.
	dc.b 171, 1	; Software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 169	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 168	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 167	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 168	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 169	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 171	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 172	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 173	; New LSB for software period.


Main_Subsong0_RegisterBlock_13:
	dc.b 81	; Initial State: software only.
	dc.b 221, 1	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 220	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 219	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 218	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 217	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 216	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 215	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 214	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 213	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 212	; New LSB for software period.


Main_Subsong0_RegisterBlock_15:
	dc.b 73	; Initial State: software only.
	dc.b 195, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_33-Main_Subsong0 + 11	; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_23:
	dc.b 89	; Initial State: software only.
	dc.b 22, 2	; Software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 20	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 18	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 16	; New LSB for software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 14	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 10	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 8	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 6	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 4	; New LSB for software period.


Main_Subsong0_RegisterBlock_25:
	dc.b 81	; Initial State: software only.
	dc.b 250, 1	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 254	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 0	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 1	; New LSB for software period.


Main_Subsong0_RegisterBlock_26:
	dc.b 81	; Initial State: software only.
	dc.b 0, 2	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 105	; Non-initial State, software only.
	dc.b 254	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_24-Main_Subsong0 + 10	; Optimization: goto common Block at index 4.

Main_Subsong0_RegisterBlock_28:
	dc.b 89	; Initial State: software only.
	dc.b 195, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_9-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_29:
	dc.b 81	; Initial State: software only.
	dc.b 170, 1	; Software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_35-Main_Subsong0 + 11	; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_30:
	dc.b 81	; Initial State: software only.
	dc.b 195, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_29-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_45:
	dc.b 89	; Initial State: software only.
	dc.b 142, 0	; Software period.

	dc.b 241	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_9-Main_Subsong0 + 4	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_46:
	dc.b 81	; Initial State: software only.
	dc.b 142, 0	; Software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_35-Main_Subsong0 + 11	; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_47:
	dc.b 73	; Initial State: software only.
	dc.b 169, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 6	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_48:
	dc.b 81	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_54:
	dc.b 73	; Initial State: software only.
	dc.b 28, 1	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 6	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_55:
	dc.b 81	; Initial State: software only.
	dc.b 253, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_105-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_56:
	dc.b 73	; Initial State: software only.
	dc.b 225, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 6	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_57:
	dc.b 81	; Initial State: software only.
	dc.b 213, 0	; Software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_35-Main_Subsong0 + 11	; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_58:
	dc.b 73	; Initial State: software only.
	dc.b 190, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 6	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_59:
	dc.b 81	; Initial State: software only.
	dc.b 169, 0	; Software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_35-Main_Subsong0 + 11	; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_61:
	dc.b 89	; Initial State: software only.
	dc.b 169, 0	; Software period.

	dc.b 241	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_9-Main_Subsong0 + 4	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_63:
	dc.b 73	; Initial State: software only.
	dc.b 213, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 6	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_64:
	dc.b 81	; Initial State: software only.
	dc.b 190, 0	; Software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_35-Main_Subsong0 + 11	; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_70:
	dc.b 81	; Initial State: software only.
	dc.b 127, 0	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_35-Main_Subsong0 + 11	; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_90:
	dc.b 73	; Initial State: software only.
	dc.b 142, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_102-Main_Subsong0 + 6	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_101:
	dc.b 89	; Initial State: software only.
	dc.b 127, 0	; Software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_9-Main_Subsong0 + 4	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_106:
	dc.b 81	; Initial State: software only.
	dc.b 225, 0	; Software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_35-Main_Subsong0 + 11	; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_110:
	dc.b 89	; Initial State: software only.
	dc.b 225, 0	; Software period.

	dc.b 241	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_9-Main_Subsong0 + 4	; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_112:
	dc.b 89	; Initial State: software only.
	dc.b 190, 0	; Software period.

	dc.b 241	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_9-Main_Subsong0 + 4	; Optimization: goto common Block at index 2.

