; Song New song, in AKY version 1.0, generated by Arkos Tracker 2.

Main_Subsong0:

; Header
	dc.b 128	; Format version: 0 and endianness: little-endian.
	dc.b 3	; How many channels are encoded.
; Frequency of the PSG index 0: 2000000Hz.
	dc.b 128, 132, 30, 0

Main_Subsong0_Linker:
; Pattern 0
	dc.w 192	; Duration in frames.
	dc.w Main_Subsong0_Track_0-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0

; Pattern 1
	dc.w 192	; Duration in frames.
	dc.w Main_Subsong0_Track_3-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0

; Pattern 2
	dc.w 192	; Duration in frames.
	dc.w Main_Subsong0_Track_18-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0

; Pattern 3
	dc.w 192	; Duration in frames.
	dc.w Main_Subsong0_Track_9-Main_Subsong0
	dc.w Main_Subsong0_Track_10-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0

; Pattern 4
Main_Subsong0_LinkerLoop:	; Loops here.
	dc.w 192	; Duration in frames.
	dc.w Main_Subsong0_Track_18-Main_Subsong0
	dc.w Main_Subsong0_Track_13-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0

; Pattern 5
	dc.w 192	; Duration in frames.
	dc.w Main_Subsong0_Track_18-Main_Subsong0
	dc.w Main_Subsong0_Track_16-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0

; Pattern 6
	dc.w 192	; Duration in frames.
	dc.w Main_Subsong0_Track_18-Main_Subsong0
	dc.w Main_Subsong0_Track_19-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0

; Pattern 7
	dc.w 192	; Duration in frames.
	dc.w Main_Subsong0_Track_21-Main_Subsong0
	dc.w Main_Subsong0_Track_22-Main_Subsong0
	dc.w Main_Subsong0_Track_23-Main_Subsong0

	dc.w 0	; Loops (duration = 0).
	dc.w Main_Subsong0_LinkerLoop-Main_Subsong0

; The tracks.
Main_Subsong0_Track_0:
	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_19-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0

Main_Subsong0_Track_3:
	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_25-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_25-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_43-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0

Main_Subsong0_Track_9:
	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_67-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_66-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_67-Main_Subsong0

Main_Subsong0_Track_10:
	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_69-Main_Subsong0

	dc.b 138	; Duration.
	dc.w Main_Subsong0_RegisterBlock_70-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_71-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_72-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_73-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_74-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_75-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_76-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_77-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_78-Main_Subsong0

Main_Subsong0_Track_13:
	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_80-Main_Subsong0

	dc.b 42	; Duration.
	dc.w Main_Subsong0_RegisterBlock_81-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_82-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_83-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_82-Main_Subsong0

Main_Subsong0_Track_16:
	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_86-Main_Subsong0

	dc.b 42	; Duration.
	dc.w Main_Subsong0_RegisterBlock_87-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_89-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0

Main_Subsong0_Track_18:
	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_95-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_101-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_95-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_113-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0

Main_Subsong0_Track_19:
	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_116-Main_Subsong0

	dc.b 42	; Duration.
	dc.w Main_Subsong0_RegisterBlock_117-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_118-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_119-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_118-Main_Subsong0

Main_Subsong0_Track_21:
	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_95-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_101-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_95-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_22-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_20-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_113-Main_Subsong0

	dc.b 12	; Duration.
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0

Main_Subsong0_Track_22:
	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_146-Main_Subsong0

	dc.b 42	; Duration.
	dc.w Main_Subsong0_RegisterBlock_147-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_148-Main_Subsong0

	dc.b 6	; Duration.
	dc.w Main_Subsong0_RegisterBlock_149-Main_Subsong0

	dc.b 42	; Duration.
	dc.w Main_Subsong0_RegisterBlock_150-Main_Subsong0

	dc.b 48	; Duration.
	dc.w Main_Subsong0_RegisterBlock_151-Main_Subsong0

Main_Subsong0_Track_23:
	dc.b 192	; Duration.
	dc.w Main_Subsong0_RegisterBlock_153-Main_Subsong0


; The RegisterBlocks.
Main_Subsong0_RegisterBlock_153:
	dc.b 0	; Initial State: no software, no hardware.

Main_Subsong0_RegisterBlock_153_Loop:
	dc.b 4	; Non-initial State, no software no hardware.

	dc.b 8	; Loop to index 1.
	dc.w Main_Subsong0_RegisterBlock_153_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_70:
	dc.b 92	; Initial State: no software, no hardware.
	dc.b 2	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 2	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 3	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 3	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 3	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 3	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 4	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 4	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 4	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 4	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 5	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 5	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 5	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 5	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 6	; Noise.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 6	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 6	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 6	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 7	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 7	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 7	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 7	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 8	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 8	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 8	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 8	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 9	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 9	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 9	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 9	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 10	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 10	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 10	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 10	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 11	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 11	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 11	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 11	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 12	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 12	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 12	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 12	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 14	; Noise.

	dc.b 204	; Non-initial State, no software no hardware.
	dc.b 14	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 14	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 14	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 15	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 15	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 15	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 15	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 16	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 16	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 16	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 16	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 17	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 17	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 17	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 17	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 18	; Noise.

	dc.b 196	; Non-initial State, no software no hardware.
	dc.b 18	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 18	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 18	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 19	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 19	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 19	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 19	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 20	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 20	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 20	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 20	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 21	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 21	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 21	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 21	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 22	; Noise.

	dc.b 188	; Non-initial State, no software no hardware.
	dc.b 22	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 22	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 22	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 23	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 23	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 23	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 23	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 24	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 24	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 24	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 24	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 25	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 25	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 25	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 25	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 26	; Noise.

	dc.b 180	; Non-initial State, no software no hardware.
	dc.b 26	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 26	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 26	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 27	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 27	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 27	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 27	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 28	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 28	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 28	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 28	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 29	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 29	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 29	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 29	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 30	; Noise.

	dc.b 172	; Non-initial State, no software no hardware.
	dc.b 30	; Noise.

	dc.b 164	; Non-initial State, no software no hardware.
	dc.b 30	; Noise.

	dc.b 164	; Non-initial State, no software no hardware.
	dc.b 30	; Noise.

	dc.b 164	; Non-initial State, no software no hardware.
	dc.b 31	; Noise.

	dc.b 164	; Non-initial State, no software no hardware.
	dc.b 31	; Noise.

	dc.b 164	; Non-initial State, no software no hardware.
	dc.b 31	; Noise.

	dc.b 164	; Non-initial State, no software no hardware.
	dc.b 31	; Noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_153-Main_Subsong0 + 1	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_82:
	dc.b 57	; Initial State: software only.
	dc.b 89, 0	; Software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 150	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 45	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 45	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 150	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_83:
	dc.b 81	; Initial State: software only.
	dc.b 89, 0	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 150	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 45	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 45	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 150	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_82-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_88:
	dc.b 57	; Initial State: software only.
	dc.b 100, 0	; Software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_89:
	dc.b 81	; Initial State: software only.
	dc.b 100, 0	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_88-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_118:
	dc.b 57	; Initial State: software only.
	dc.b 113, 0	; Software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 150	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 45	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 45	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_82-Main_Subsong0 + 70	; Optimization: goto common Block at index 43.

Main_Subsong0_RegisterBlock_119:
	dc.b 81	; Initial State: software only.
	dc.b 113, 0	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 150	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 45	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 45	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 225	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_82-Main_Subsong0 + 6	; Optimization: goto common Block at index 3.

Main_Subsong0_RegisterBlock_148:
	dc.b 57	; Initial State: software only.
	dc.b 89, 0	; Software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_151:
	dc.b 57	; Initial State: software only.
	dc.b 89, 0	; Software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 142	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 142	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_148-Main_Subsong0 + 67	; Optimization: goto common Block at index 41.

Main_Subsong0_RegisterBlock_81:
	dc.b 73	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_83-Main_Subsong0 + 12	; Optimization: goto common Block at index 7.

Main_Subsong0_RegisterBlock_87:
	dc.b 73	; Initial State: software only.
	dc.b 179, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_89-Main_Subsong0 + 12	; Optimization: goto common Block at index 7.

Main_Subsong0_RegisterBlock_117:
	dc.b 73	; Initial State: software only.
	dc.b 201, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_119-Main_Subsong0 + 12	; Optimization: goto common Block at index 7.

Main_Subsong0_RegisterBlock_147:
	dc.b 73	; Initial State: software only.
	dc.b 134, 0	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 201	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_148-Main_Subsong0 + 3	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_150:
	dc.b 73	; Initial State: software only.
	dc.b 142, 0	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 229	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 37	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 225	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 221	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 142	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_147-Main_Subsong0 + 58	; Optimization: goto common Block at index 35.

Main_Subsong0_RegisterBlock_0:
	dc.b 131	; Initial State : software and hardware.
	dc.b 152, 5	; Software period.
	dc.b 22, 0	; Hardware period.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 71	; New LSB for software period.
	dc.b 6	; New MSB for software period, maybe with noise.

	dc.b 105	; Non-initial State, software only.
	dc.b 167	; New LSB for software period.


Main_Subsong0_RegisterBlock_18:
	dc.b 131	; Initial State : software and hardware.
	dc.b 71, 5	; Software period.
	dc.b 21, 0	; Hardware period.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 152	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 71	; New LSB for software period.
	dc.b 6	; New MSB for software period, maybe with noise.


Main_Subsong0_RegisterBlock_19:
	dc.b 131	; Initial State : software and hardware.
	dc.b 252, 4	; Software period.
	dc.b 20, 0	; Hardware period.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 71	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 105	; Non-initial State, software only.
	dc.b 152	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.


Main_Subsong0_RegisterBlock_20:
	dc.b 131	; Initial State : software and hardware.
	dc.b 180, 4	; Software period.
	dc.b 19, 0	; Hardware period.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 71	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 105	; Non-initial State, software only.
	dc.b 152	; New LSB for software period.


Main_Subsong0_RegisterBlock_22:
	dc.b 109	; Initial State: software only.
	dc.b 31	; Noise.
	dc.b 188, 3	; Software period.

	dc.b 125	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 253	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 253	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 105	; Non-initial State, software only.
	dc.b 152	; New LSB for software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0 + 9	; Optimization: goto common Block at index 5.

Main_Subsong0_RegisterBlock_43:
	dc.b 109	; Initial State: software only.
	dc.b 31	; Noise.
	dc.b 188, 3	; Software period.

	dc.b 125	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 253	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 253	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 233	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_19-Main_Subsong0 + 9	; Optimization: goto common Block at index 5.

Main_Subsong0_RegisterBlock_67:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 177	; Non-initial State, software only.
	dc.b 194	; New MSB for software period, maybe with noise.
	dc.b 13	; New noise.

	dc.b 169	; Non-initial State, software only.
	dc.b 130	; New MSB for software period, maybe with noise.

	dc.b 233	; Non-initial State, software only.
	dc.b 71	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_18-Main_Subsong0 + 11	; Optimization: goto common Block at index 7.

Main_Subsong0_RegisterBlock_101:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 177	; Non-initial State, software only.
	dc.b 194	; New MSB for software period, maybe with noise.
	dc.b 13	; New noise.

	dc.b 169	; Non-initial State, software only.
	dc.b 130	; New MSB for software period, maybe with noise.

	dc.b 233	; Non-initial State, software only.
	dc.b 152	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0 + 11	; Optimization: goto common Block at index 7.

Main_Subsong0_RegisterBlock_113:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 177	; Non-initial State, software only.
	dc.b 194	; New MSB for software period, maybe with noise.
	dc.b 13	; New noise.

	dc.b 169	; Non-initial State, software only.
	dc.b 130	; New MSB for software period, maybe with noise.

	dc.b 233	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_19-Main_Subsong0 + 11	; Optimization: goto common Block at index 7.

Main_Subsong0_RegisterBlock_1:
	dc.b 131	; Initial State : software and hardware.
	dc.b 152, 5	; Software period.
	dc.b 22, 0	; Hardware period.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_25:
	dc.b 109	; Initial State: software only.
	dc.b 31	; Noise.
	dc.b 188, 3	; Software period.

	dc.b 125	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 253	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 253	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 245	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.
	dc.b 9	; New MSB for software period, maybe with noise.

	dc.b 4	; Non-initial State, no software no hardware.


Main_Subsong0_RegisterBlock_65:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_67-Main_Subsong0 + 4	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_66:
	dc.b 101	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 241	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 113	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 113	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 169	; Non-initial State, software only.
	dc.b 194	; New MSB for software period, maybe with noise.
	dc.b 13	; New noise.

	dc.b 161	; Non-initial State, software only.
	dc.b 130	; New MSB for software period, maybe with noise.


Main_Subsong0_RegisterBlock_69:
	dc.b 100	; Initial State: no software, no hardware.
	dc.b 1	; Noise.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 1	; Noise.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 1	; Noise.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 1	; Noise.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 2	; Noise.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 2	; Noise.


Main_Subsong0_RegisterBlock_71:
	dc.b 17	; Initial State: software only.
	dc.b 89, 0	; Software period.

	dc.b 9	; Non-initial State, software only.

	dc.b 77	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 13	; Non-initial State, software only.

	dc.b 81	; Non-initial State, software only.
	dc.b 150	; New LSB for software period.

	dc.b 17	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_72:
	dc.b 33	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 17	; Non-initial State, software only.

	dc.b 81	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 17	; Non-initial State, software only.

	dc.b 81	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 17	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_73:
	dc.b 41	; Initial State: software only.
	dc.b 45, 1	; Software period.

	dc.b 21	; Non-initial State, software only.

	dc.b 85	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 21	; Non-initial State, software only.

	dc.b 85	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 21	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_74:
	dc.b 41	; Initial State: software only.
	dc.b 222, 1	; Software period.

	dc.b 21	; Non-initial State, software only.

	dc.b 213	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 21	; Non-initial State, software only.

	dc.b 85	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 21	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_75:
	dc.b 49	; Initial State: software only.
	dc.b 204, 2	; Software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 90	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_76:
	dc.b 49	; Initial State: software only.
	dc.b 222, 1	; Software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.

	dc.b 89	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 25	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_77:
	dc.b 57	; Initial State: software only.
	dc.b 45, 1	; Software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_83-Main_Subsong0 + 61	; Optimization: goto common Block at index 38.

Main_Subsong0_RegisterBlock_78:
	dc.b 57	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_83-Main_Subsong0 + 70	; Optimization: goto common Block at index 43.

Main_Subsong0_RegisterBlock_80:
	dc.b 65	; Initial State: software only.
	dc.b 89, 0	; Software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 150	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_86:
	dc.b 65	; Initial State: software only.
	dc.b 100, 0	; Software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_95:
	dc.b 117	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 170, 1	; Software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 121	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.

	dc.b 228	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.


Main_Subsong0_RegisterBlock_116:
	dc.b 65	; Initial State: software only.
	dc.b 113, 0	; Software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 150	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_146:
	dc.b 65	; Initial State: software only.
	dc.b 89, 0	; Software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.


Main_Subsong0_RegisterBlock_149:
	dc.b 65	; Initial State: software only.
	dc.b 89, 0	; Software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 101	; Non-initial State, software only.
	dc.b 119	; New LSB for software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 105	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.

	dc.b 41	; Non-initial State, software only.


