; Events generated by Arkos Tracker 2.

	; 0

Events:
	dc.w 1537	; Wait for 1536 frames.
	dc.w 0

Events_Loop:
	dc.w 6913	; Wait for 6912 frames.
	dc.w 0

	dc.w 0	; End of sequence.
	dc.l Events_Loop	; Loops here.
