; Song SID_Test_001, in AKY version 1.0, generated by Arkos Tracker 2.

Main_Subsong0:

	; 0

; Header
	dc.b 128	; Format version: 0 and endianness: little-endian.
	dc.b 3	; How many channels are encoded.
; Frequency of the PSG index 0: 2000000Hz.
	dc.b 128, 132, 30, 0

Main_Subsong0_Linker:
; Pattern 0
Main_Subsong0_LinkerLoop:	; Loops here.
	dc.w 472	; Duration in frames.
	dc.w Main_Subsong0_Track_0 - Main_Subsong0
	dc.w Main_Subsong0_Track_1 - Main_Subsong0
	dc.w Main_Subsong0_Track_2 - Main_Subsong0

	dc.w 0	; Loops (duration = 0).
	dc.w Main_Subsong0_LinkerLoop - Main_Subsong0

; The tracks.
Main_Subsong0_Track_0:
	dc.b 1	; Duration.
	dc.w Main_Subsong0_RegisterBlock_21 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_8 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_8 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_8 - Main_Subsong0

	dc.b 255	; Duration.
	dc.w Main_Subsong0_RegisterBlock_8 - Main_Subsong0

	dc.b 90	; Duration.
	dc.w Main_Subsong0_RegisterBlock_21 - Main_Subsong0

Main_Subsong0_Track_1:
	dc.b 145	; Duration.
	dc.w Main_Subsong0_RegisterBlock_21 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_12 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_12 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_19 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_19 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_12 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_12 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_19 - Main_Subsong0

	dc.b 201	; Duration.
	dc.w Main_Subsong0_RegisterBlock_19 - Main_Subsong0

Main_Subsong0_Track_2:
	dc.b 255	; Duration.
	dc.w Main_Subsong0_RegisterBlock_21 - Main_Subsong0

	dc.b 34	; Duration.
	dc.w Main_Subsong0_RegisterBlock_21 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_23 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_23 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_23 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_23 - Main_Subsong0

	dc.b 18	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30 - Main_Subsong0

	dc.b 57	; Duration.
	dc.w Main_Subsong0_RegisterBlock_30 - Main_Subsong0


; The RegisterBlocks.
Main_Subsong0_RegisterBlock_8:
	dc.b 105	; Initial State: software only.
	dc.b 126, 2	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 53	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 25	; Non-initial State, software only.

	dc.b 21	; Non-initial State, software only.

	dc.b 17	; Non-initial State, software only.

	dc.b 13	; Non-initial State, software only.

	dc.b 9	; Non-initial State, software only.

	dc.b 5	; Non-initial State, software only.

Main_Subsong0_RegisterBlock_8_Loop:
	dc.b 4	; Non-initial State, no software no hardware.

	dc.b 8	; Loop to index 15.
	dc.w Main_Subsong0_RegisterBlock_8_Loop - Main_Subsong0


Main_Subsong0_RegisterBlock_21:
	dc.b 0	; Initial State: no software, no hardware.

Main_Subsong0_RegisterBlock_21_Loop:
	dc.b 4	; Non-initial State, no software no hardware.

	dc.b 8	; Loop to index 1.
	dc.w Main_Subsong0_RegisterBlock_21_Loop - Main_Subsong0


Main_Subsong0_RegisterBlock_19:
	dc.b 105	; Initial State: software only.
	dc.b 204, 2	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_8 + 3 - Main_Subsong0	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_11:
	dc.b 0	; Initial State: no software, no hardware.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_8 + 17 - Main_Subsong0	; Optimization: goto common Block at index 15.

Main_Subsong0_RegisterBlock_9:
	dc.b 0	; Initial State: no software, no hardware.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_8 + 17 - Main_Subsong0	; Optimization: goto common Block at index 15.

Main_Subsong0_RegisterBlock_30:
	dc.b 105	; Initial State: software only.
	dc.b 36, 3	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_8 + 3 - Main_Subsong0	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_1:
	dc.b 105	; Initial State: software only.
	dc.b 222, 1	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_8 + 3 - Main_Subsong0	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_3:
	dc.b 105	; Initial State: software only.
	dc.b 126, 2	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_8 + 3 - Main_Subsong0	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_12:
	dc.b 105	; Initial State: software only.
	dc.b 24, 2	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_8 + 3 - Main_Subsong0	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_14:
	dc.b 105	; Initial State: software only.
	dc.b 204, 2	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_8 + 3 - Main_Subsong0	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_23:
	dc.b 105	; Initial State: software only.
	dc.b 90, 2	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_8 + 3 - Main_Subsong0	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_25:
	dc.b 105	; Initial State: software only.
	dc.b 36, 3	; Software period.

	dc.b 8
	dc.w Main_Subsong0_RegisterBlock_8 + 3 - Main_Subsong0	; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_0:
	dc.b 0	; Initial State: no software, no hardware.


