;Events generated by Arkos Tracker 2.

Main_Events:
Main_Events_Loop:
	dc.w 1	;Wait for 0 frames.
	dc.w 240

	dc.w 37	;Wait for 36 frames.
	dc.w 244

	dc.w 36	;Wait for 35 frames.
	dc.w 243

	dc.w 36	;Wait for 35 frames.
	dc.w 247

	dc.w 36	;Wait for 35 frames.
	dc.w 240

	dc.w 36	;Wait for 35 frames.
	dc.w 242

	dc.w 36	;Wait for 35 frames.
	dc.w 245

	dc.w 36	;Wait for 35 frames.
	dc.w 247

	dc.w 36	;Wait for 35 frames.
	dc.w 240

	dc.w 36	;Wait for 35 frames.
	dc.w 241

	dc.w 36	;Wait for 35 frames.
	dc.w 246

	dc.w 36	;Wait for 35 frames.
	dc.w 247

	dc.w 75	;Wait for 74 frames.
	dc.w 0

	dc.w 0	;End of sequence.
	dc.l Main_Events_Loop	;Loops here.
