;Events generated by Arkos Tracker 2.

Main_Events:
Main_Events_Loop:
	dc.w 1	;Wait for 0 frames.
	dc.b 240

	dc.w 37	;Wait for 36 frames.
	dc.b 244

	dc.w 36	;Wait for 35 frames.
	dc.b 243

	dc.w 36	;Wait for 35 frames.
	dc.b 247

	dc.w 36	;Wait for 35 frames.
	dc.b 240

	dc.w 36	;Wait for 35 frames.
	dc.b 242

	dc.w 36	;Wait for 35 frames.
	dc.b 245

	dc.w 36	;Wait for 35 frames.
	dc.b 247

	dc.w 36	;Wait for 35 frames.
	dc.b 240

	dc.w 36	;Wait for 35 frames.
	dc.b 241

	dc.w 36	;Wait for 35 frames.
	dc.b 246

	dc.w 36	;Wait for 35 frames.
	dc.b 247

	dc.w 75	;Wait for 74 frames.
	dc.b 0

	dc.w 0	;End of sequence.
	dc.w Main_Events_Loop	;Loops here.
