; Events generated by Arkos Tracker 2.

	; 0

Events:
	dc.w 769	; Wait for 768 frames.
	dc.w 0

Events_Loop:
	dc.w 3841	; Wait for 3840 frames.
	dc.w 0

	dc.w 0	; End of sequence.
	dc.l Events_Loop	; Loops here.
