; Events generated by Arkos Tracker 2.

	; 0

Events:
	dc.w 1	; Wait for 0 frames.
	dc.w 241

	dc.w 76	; Wait for 75 frames.
	dc.w 245

	dc.w 71	; Wait for 70 frames.
	dc.w 241

	dc.w 5	; Wait for 4 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 0

Events_Loop:
	dc.w 1	; Wait for 0 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 14	; Wait for 13 frames.
	dc.w 240

	dc.w 5	; Wait for 4 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 19	; Wait for 18 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 1

	dc.w 10	; Wait for 9 frames.
	dc.w 241

	dc.w 9	; Wait for 8 frames.
	dc.w 2

	dc.w 19	; Wait for 18 frames.
	dc.w 0

	dc.w 0	; End of sequence.
	dc.l Events_Loop-Events	; Loops here.
