; Song You never can tell, in AKY version 1.0, generated by Arkos Tracker 2.

Subsong0:

	; 0

; Header
	dc.b 128	; Format version: 0 and endianness: little-endian.
	dc.b 3	; How many channels are encoded.
; Frequency of the PSG index 0: 2000000Hz.
	dc.b 128, 132, 30, 0

Subsong0_Linker:
; Pattern 0
	dc.w 38	; Duration in frames.
	dc.w Subsong0_Track_2 - Subsong0
	dc.w Subsong0_Track_1 - Subsong0
	dc.w Subsong0_Track_2 - Subsong0

; Pattern 1
Subsong0_LinkerLoop:	; Loops here.
	dc.w 152	; Duration in frames.
	dc.w Subsong0_Track_24 - Subsong0
	dc.w Subsong0_Track_4 - Subsong0
	dc.w Subsong0_Track_26 - Subsong0

; Pattern 2
	dc.w 152	; Duration in frames.
	dc.w Subsong0_Track_24 - Subsong0
	dc.w Subsong0_Track_7 - Subsong0
	dc.w Subsong0_Track_26 - Subsong0

; Pattern 3
	dc.w 152	; Duration in frames.
	dc.w Subsong0_Track_24 - Subsong0
	dc.w Subsong0_Track_10 - Subsong0
	dc.w Subsong0_Track_26 - Subsong0

; Pattern 4
	dc.w 152	; Duration in frames.
	dc.w Subsong0_Track_21 - Subsong0
	dc.w Subsong0_Track_13 - Subsong0
	dc.w Subsong0_Track_23 - Subsong0

; Pattern 5
	dc.w 152	; Duration in frames.
	dc.w Subsong0_Track_21 - Subsong0
	dc.w Subsong0_Track_16 - Subsong0
	dc.w Subsong0_Track_23 - Subsong0

; Pattern 6
	dc.w 152	; Duration in frames.
	dc.w Subsong0_Track_21 - Subsong0
	dc.w Subsong0_Track_19 - Subsong0
	dc.w Subsong0_Track_23 - Subsong0

; Pattern 7
	dc.w 152	; Duration in frames.
	dc.w Subsong0_Track_21 - Subsong0
	dc.w Subsong0_Track_22 - Subsong0
	dc.w Subsong0_Track_23 - Subsong0

; Pattern 8
	dc.w 152	; Duration in frames.
	dc.w Subsong0_Track_24 - Subsong0
	dc.w Subsong0_Track_25 - Subsong0
	dc.w Subsong0_Track_26 - Subsong0

	dc.w 0	; Loops (duration = 0).
	dc.w Subsong0_LinkerLoop - Subsong0

; The tracks.
Subsong0_Track_1:
	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_2 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_23 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_41 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_5 - Subsong0

Subsong0_Track_2:
	dc.b 38	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

Subsong0_Track_4:
	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_9 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_10 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_16 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_12 - Subsong0

	dc.b 19	; Duration.
	dc.w Subsong0_RegisterBlock_13 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_2 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_16 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_2 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_19 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_20 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_16 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_22 - Subsong0

	dc.b 19	; Duration.
	dc.w Subsong0_RegisterBlock_23 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_24 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_59 - Subsong0

Subsong0_Track_7:
	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_27 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_28 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_29 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_30 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_31 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_33 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_38 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_36 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_37 - Subsong0

	dc.b 19	; Duration.
	dc.w Subsong0_RegisterBlock_38 - Subsong0

	dc.b 29	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_23 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_41 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_42 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_43 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_44 - Subsong0

Subsong0_Track_10:
	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_46 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_23 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_16 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_12 - Subsong0

	dc.b 19	; Duration.
	dc.w Subsong0_RegisterBlock_50 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_52 - Subsong0

	dc.b 19	; Duration.
	dc.w Subsong0_RegisterBlock_23 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_24 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_55 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_24 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_55 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_59 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_2 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_62 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_63 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_97 - Subsong0

Subsong0_Track_13:
	dc.b 19	; Duration.
	dc.w Subsong0_RegisterBlock_66 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_67 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_210 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_69 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_73 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_38 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_72 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_73 - Subsong0

	dc.b 38	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_2 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_23 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_118 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_79 - Subsong0

Subsong0_Track_16:
	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_81 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_82 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_83 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_84 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_52 - Subsong0

	dc.b 19	; Duration.
	dc.w Subsong0_RegisterBlock_23 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_148 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_89 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_148 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_149 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_92 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_93 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_94 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_24 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_55 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_97 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_62 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_99 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_59 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_2 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_62 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_63 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_97 - Subsong0

Subsong0_Track_19:
	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_107 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_108 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_67 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_210 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_69 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_73 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_38 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_72 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_73 - Subsong0

	dc.b 38	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_23 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_118 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_119 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_120 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_121 - Subsong0

Subsong0_Track_21:
	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_123 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_123 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_125 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_126 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_127 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_127 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_125 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_126 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_123 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_123 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_125 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_126 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_127 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_127 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_125 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_126 - Subsong0

Subsong0_Track_22:
	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_140 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_2 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_56 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_52 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_145 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_146 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_147 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_148 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_149 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_148 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_89 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_152 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_153 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_154 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_152 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_153 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_154 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_152 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_153 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_154 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_152 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_162 - Subsong0

Subsong0_Track_23:
	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_164 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_168 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_168 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_168 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_217 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_164 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_168 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_168 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_168 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_217 - Subsong0

Subsong0_Track_24:
	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_181 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_181 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_183 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_184 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_185 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_185 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_183 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_184 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_181 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_181 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_183 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_184 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_185 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_185 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_183 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_184 - Subsong0

Subsong0_Track_25:
	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_198 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_199 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_200 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_201 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_31 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_201 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_31 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_201 - Subsong0

	dc.b 4	; Duration.
	dc.w Subsong0_RegisterBlock_31 - Subsong0

	dc.b 5	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_210 - Subsong0

	dc.b 66	; Duration.
	dc.w Subsong0_RegisterBlock_211 - Subsong0

Subsong0_Track_26:
	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_164 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_217 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_217 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_217 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_220 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_164 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_217 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_217 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_217 - Subsong0

	dc.b 10	; Duration.
	dc.w Subsong0_RegisterBlock_166 - Subsong0

	dc.b 9	; Duration.
	dc.w Subsong0_RegisterBlock_220 - Subsong0


; The RegisterBlocks.
Subsong0_RegisterBlock_211:
	dc.b 0	; Initial State: no software, no hardware.

Subsong0_RegisterBlock_211_Loop:
	dc.b 4	; Non-initial State, no software no hardware.

	dc.b 8	; Loop to index 1.
	dc.w Subsong0_RegisterBlock_211_Loop - Subsong0


Subsong0_RegisterBlock_7:
	dc.b 0	; Initial State: no software, no hardware.

	dc.b 8
	dc.w Subsong0_RegisterBlock_211 + 1 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_13:
	dc.b 89	; Initial State: software only.
	dc.b 23, 1	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 18	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 17	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 16	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 15	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 14	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 9	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 4	; New LSB for software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 105	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 1	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 229	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 109	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.


Subsong0_RegisterBlock_23:
	dc.b 73	; Initial State: software only.
	dc.b 140, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 109	; Non-initial State, software only.
	dc.b 26	; New LSB for software period.

Subsong0_RegisterBlock_23_Loop:
	dc.b 109	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 30	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 32	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 30	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 26	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 26	; New LSB for software period.

	dc.b 8	; Loop to index 3.
	dc.w Subsong0_RegisterBlock_23_Loop - Subsong0


Subsong0_RegisterBlock_38:
	dc.b 105	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 237	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

Subsong0_RegisterBlock_38_Loop:
	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 8	; Loop to index 7.
	dc.w Subsong0_RegisterBlock_38_Loop - Subsong0


Subsong0_RegisterBlock_50:
	dc.b 89	; Initial State: software only.
	dc.b 24, 1	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 20	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 16	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 8	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 4	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 0	; New LSB for software period.

Subsong0_RegisterBlock_50_Loop:
	dc.b 229	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 8	; Loop to index 7.
	dc.w Subsong0_RegisterBlock_50_Loop - Subsong0


Subsong0_RegisterBlock_66:
	dc.b 65	; Initial State: software only.
	dc.b 98, 1	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 106	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 98	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 106	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 73	; Non-initial State, software only.
	dc.b 98	; New LSB for software period.

	dc.b 81	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 77	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.


Subsong0_RegisterBlock_0:
	dc.b 0	; Initial State: no software, no hardware.

	dc.b 8
	dc.w Subsong0_RegisterBlock_211 + 1 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_3:
	dc.b 73	; Initial State: software only.
	dc.b 140, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_23 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_12:
	dc.b 65	; Initial State: software only.
	dc.b 28, 1	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 21	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.


Subsong0_RegisterBlock_16:
	dc.b 73	; Initial State: software only.
	dc.b 142, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

Subsong0_RegisterBlock_16_Loop:
	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 8	; Loop to index 2.
	dc.w Subsong0_RegisterBlock_16_Loop - Subsong0


Subsong0_RegisterBlock_19:
	dc.b 73	; Initial State: software only.
	dc.b 58, 1	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 53	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 48	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 43	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 38	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 33	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_16 + 8 - Subsong0	; Optimization: goto common Block at index 4.

Subsong0_RegisterBlock_24:
	dc.b 73	; Initial State: software only.
	dc.b 190, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 123	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Subsong0_RegisterBlock_16 + 6 - Subsong0	; Optimization: goto common Block at index 2.

Subsong0_RegisterBlock_27:
	dc.b 73	; Initial State: software only.
	dc.b 59, 1	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 67	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 59	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.


Subsong0_RegisterBlock_33:
	dc.b 105	; Initial State: software only.
	dc.b 82, 1	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 164	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 237	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 164	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.


Subsong0_RegisterBlock_36:
	dc.b 105	; Initial State: software only.
	dc.b 239, 0	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 237	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.


Subsong0_RegisterBlock_46:
	dc.b 73	; Initial State: software only.
	dc.b 239, 0	; Software period.

	dc.b 45	; Non-initial State, software only.

Subsong0_RegisterBlock_46_Loop:
	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 8
	dc.w Subsong0_RegisterBlock_16 + 6 - Subsong0	; Optimization: goto common Block at index 2.

Subsong0_RegisterBlock_52:
	dc.b 65	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_12 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_56:
	dc.b 73	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Subsong0_RegisterBlock_16 + 6 - Subsong0	; Optimization: goto common Block at index 2.

Subsong0_RegisterBlock_59:
	dc.b 73	; Initial State: software only.
	dc.b 157, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 59	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Subsong0_RegisterBlock_27 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_67:
	dc.b 105	; Initial State: software only.
	dc.b 250, 1	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 237	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 250	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.


Subsong0_RegisterBlock_69:
	dc.b 105	; Initial State: software only.
	dc.b 195, 1	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 237	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 134	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 195	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.


Subsong0_RegisterBlock_73:
	dc.b 105	; Initial State: software only.
	dc.b 170, 1	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 83	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 237	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 83	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 170	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.


Subsong0_RegisterBlock_93:
	dc.b 81	; Initial State: software only.
	dc.b 67, 1	; Software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 64	; New LSB for software period.

Subsong0_RegisterBlock_93_Loop:
	dc.b 109	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 41	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 8	; Loop to index 2.
	dc.w Subsong0_RegisterBlock_93_Loop - Subsong0


Subsong0_RegisterBlock_97:
	dc.b 73	; Initial State: software only.
	dc.b 177, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 98	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 109	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 106	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 98	; New LSB for software period.


Subsong0_RegisterBlock_107:
	dc.b 73	; Initial State: software only.
	dc.b 98, 1	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 106	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 98	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.


Subsong0_RegisterBlock_123:
	dc.b 121	; Initial State: software only.
	dc.b 247, 9	; Software period.

	dc.b 57	; Non-initial State, software only.

	dc.b 53	; Non-initial State, software only.

	dc.b 49	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.

Subsong0_RegisterBlock_123_Loop:
	dc.b 41	; Non-initial State, software only.

	dc.b 8	; Loop to index 5.
	dc.w Subsong0_RegisterBlock_123_Loop - Subsong0


Subsong0_RegisterBlock_125:
	dc.b 121	; Initial State: software only.
	dc.b 97, 8	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_123 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_127:
	dc.b 121	; Initial State: software only.
	dc.b 167, 6	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_123 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_140:
	dc.b 65	; Initial State: software only.
	dc.b 251, 0	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.

	dc.b 225	; Non-initial State, software only.
	dc.b 1	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 225	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 93	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 85	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.


Subsong0_RegisterBlock_147:
	dc.b 73	; Initial State: software only.
	dc.b 26, 1	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 26	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 30	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 32	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 30	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 26	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.


Subsong0_RegisterBlock_149:
	dc.b 65	; Initial State: software only.
	dc.b 102, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_12 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_152:
	dc.b 73	; Initial State: software only.
	dc.b 93, 0	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 186	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 188	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 192	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 194	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 192	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 188	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 186	; New LSB for software period.


Subsong0_RegisterBlock_164:
	dc.b 101	; Initial State: software only.
	dc.b 31	; Noise.
	dc.b 188, 3	; Software period.

	dc.b 121	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 249	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 4	; New MSB for software period, maybe with noise.

	dc.b 249	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.
	dc.b 5	; New MSB for software period, maybe with noise.

	dc.b 241	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.
	dc.b 9	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Subsong0_RegisterBlock_211 + 1 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_166:
	dc.b 109	; Initial State: software only.
	dc.b 17	; Noise.
	dc.b 123, 1	; Software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.

	dc.b 241	; Non-initial State, software only.
	dc.b 56	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 113	; Non-initial State, software only.
	dc.b 126	; New LSB for software period.

	dc.b 220	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 212	; Non-initial State, no software no hardware.
	dc.b 13	; Noise.

	dc.b 8
	dc.w Subsong0_RegisterBlock_211 + 1 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_168:
	dc.b 81	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 213	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 213	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.


Subsong0_RegisterBlock_181:
	dc.b 121	; Initial State: software only.
	dc.b 119, 7	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_123 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_183:
	dc.b 121	; Initial State: software only.
	dc.b 71, 6	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_123 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_185:
	dc.b 121	; Initial State: software only.
	dc.b 252, 4	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_123 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_201:
	dc.b 105	; Initial State: software only.
	dc.b 146, 1	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 237	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 146	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.


Subsong0_RegisterBlock_210:
	dc.b 105	; Initial State: software only.
	dc.b 222, 1	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 188	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 237	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 188	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 222	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.


Subsong0_RegisterBlock_217:
	dc.b 81	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 159	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.


Subsong0_RegisterBlock_11:
	dc.b 73	; Initial State: software only.
	dc.b 142, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_16 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_20:
	dc.b 81	; Initial State: software only.
	dc.b 28, 1	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 25	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.


Subsong0_RegisterBlock_22:
	dc.b 81	; Initial State: software only.
	dc.b 28, 1	; Software period.

	dc.b 41	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.

	dc.b 25	; Non-initial State, software only.

	dc.b 29	; Non-initial State, software only.


Subsong0_RegisterBlock_25:
	dc.b 73	; Initial State: software only.
	dc.b 157, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_59 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_28:
	dc.b 81	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 67	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 65	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 59	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 61	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 63	; New LSB for software period.


Subsong0_RegisterBlock_37:
	dc.b 105	; Initial State: software only.
	dc.b 12, 1	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 237	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 24	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.


Subsong0_RegisterBlock_51:
	dc.b 73	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_56 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_64:
	dc.b 73	; Initial State: software only.
	dc.b 177, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_97 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_68:
	dc.b 105	; Initial State: software only.
	dc.b 222, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_210 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_70:
	dc.b 105	; Initial State: software only.
	dc.b 170, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_73 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_72:
	dc.b 105	; Initial State: software only.
	dc.b 102, 1	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.

	dc.b 237	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 45	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 204	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 41	; Non-initial State, software only.

	dc.b 233	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.


Subsong0_RegisterBlock_108:
	dc.b 81	; Initial State: software only.
	dc.b 102, 1	; Software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 106	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 104	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 98	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 100	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.


Subsong0_RegisterBlock_126:
	dc.b 121	; Initial State: software only.
	dc.b 233, 7	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_123 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_148:
	dc.b 73	; Initial State: software only.
	dc.b 179, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 102	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Subsong0_RegisterBlock_16 + 6 - Subsong0	; Optimization: goto common Block at index 2.

Subsong0_RegisterBlock_162:
	dc.b 81	; Initial State: software only.
	dc.b 188, 0	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 192	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 194	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 192	; New LSB for software period.

	dc.b 97	; Non-initial State, software only.
	dc.b 190	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 188	; New LSB for software period.

	dc.b 89	; Non-initial State, software only.
	dc.b 186	; New LSB for software period.

	dc.b 93	; Non-initial State, software only.
	dc.b 188	; New LSB for software period.


Subsong0_RegisterBlock_165:
	dc.b 81	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_168 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_171:
	dc.b 81	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_217 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_184:
	dc.b 121	; Initial State: software only.
	dc.b 237, 5	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_123 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_200:
	dc.b 89	; Initial State: software only.
	dc.b 237, 0	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 235	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 243	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.


Subsong0_RegisterBlock_220:
	dc.b 81	; Initial State: software only.
	dc.b 142, 0	; Software period.

	dc.b 37	; Non-initial State, software only.

	dc.b 97	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 142	; New LSB for software period.

	dc.b 29	; Non-initial State, software only.

	dc.b 93	; Non-initial State, software only.
	dc.b 179	; New LSB for software period.


Subsong0_RegisterBlock_2:
	dc.b 73	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 33	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 37	; Non-initial State, software only.

	dc.b 33	; Non-initial State, software only.


Subsong0_RegisterBlock_5:
	dc.b 73	; Initial State: software only.
	dc.b 253, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_2 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_9:
	dc.b 73	; Initial State: software only.
	dc.b 125, 0	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 245	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 243	; New LSB for software period.


Subsong0_RegisterBlock_10:
	dc.b 73	; Initial State: software only.
	dc.b 241, 0	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_16 + 7 - Subsong0	; Optimization: goto common Block at index 3.

Subsong0_RegisterBlock_29:
	dc.b 105	; Initial State: software only.
	dc.b 144, 1	; Software period.

	dc.b 117	; Non-initial State, software only.
	dc.b 142	; New LSB for software period.

	dc.b 241	; Non-initial State, software only.
	dc.b 34	; New LSB for software period.
	dc.b 3	; New MSB for software period, maybe with noise.

	dc.b 113	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 148	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.


Subsong0_RegisterBlock_30:
	dc.b 89	; Initial State: software only.
	dc.b 146, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_201 + 12 - Subsong0	; Optimization: goto common Block at index 6.

Subsong0_RegisterBlock_41:
	dc.b 73	; Initial State: software only.
	dc.b 127, 0	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_50 + 18 - Subsong0	; Optimization: goto common Block at index 8.

Subsong0_RegisterBlock_42:
	dc.b 65	; Initial State: software only.
	dc.b 253, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_12 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_44:
	dc.b 81	; Initial State: software only.
	dc.b 239, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_16 + 9 - Subsong0	; Optimization: goto common Block at index 5.

Subsong0_RegisterBlock_55:
	dc.b 73	; Initial State: software only.
	dc.b 123, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_2 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_62:
	dc.b 73	; Initial State: software only.
	dc.b 169, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 82	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Subsong0_RegisterBlock_50 + 18 - Subsong0	; Optimization: goto common Block at index 8.

Subsong0_RegisterBlock_63:
	dc.b 65	; Initial State: software only.
	dc.b 82, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_12 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_79:
	dc.b 73	; Initial State: software only.
	dc.b 12, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_2 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_81:
	dc.b 73	; Initial State: software only.
	dc.b 131, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 6	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 109	; Non-initial State, software only.
	dc.b 3	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 0	; New LSB for software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.


Subsong0_RegisterBlock_82:
	dc.b 73	; Initial State: software only.
	dc.b 253, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_16 + 6 - Subsong0	; Optimization: goto common Block at index 2.

Subsong0_RegisterBlock_84:
	dc.b 81	; Initial State: software only.
	dc.b 255, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 1	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 225	; Non-initial State, software only.
	dc.b 255	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.

	dc.b 93	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.


Subsong0_RegisterBlock_89:
	dc.b 73	; Initial State: software only.
	dc.b 102, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_2 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_90:
	dc.b 73	; Initial State: software only.
	dc.b 179, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_148 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_91:
	dc.b 65	; Initial State: software only.
	dc.b 102, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_12 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_94:
	dc.b 81	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_22 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_99:
	dc.b 73	; Initial State: software only.
	dc.b 82, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_2 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_118:
	dc.b 73	; Initial State: software only.
	dc.b 134, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 12	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 8
	dc.w Subsong0_RegisterBlock_50 + 18 - Subsong0	; Optimization: goto common Block at index 8.

Subsong0_RegisterBlock_119:
	dc.b 65	; Initial State: software only.
	dc.b 12, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_12 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_121:
	dc.b 81	; Initial State: software only.
	dc.b 253, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_16 + 9 - Subsong0	; Optimization: goto common Block at index 5.

Subsong0_RegisterBlock_146:
	dc.b 81	; Initial State: software only.
	dc.b 30, 1	; Software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 28	; New LSB for software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_50 + 18 - Subsong0	; Optimization: goto common Block at index 8.

Subsong0_RegisterBlock_154:
	dc.b 73	; Initial State: software only.
	dc.b 239, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_2 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_198:
	dc.b 73	; Initial State: software only.
	dc.b 122, 0	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 243	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 242	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 240	; New LSB for software period.


Subsong0_RegisterBlock_199:
	dc.b 73	; Initial State: software only.
	dc.b 243, 0	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 237	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 235	; New LSB for software period.


Subsong0_RegisterBlock_1:
	dc.b 73	; Initial State: software only.
	dc.b 159, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_56 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_4:
	dc.b 73	; Initial State: software only.
	dc.b 127, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_41 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_31:
	dc.b 105	; Initial State: software only.
	dc.b 123, 1	; Software period.

	dc.b 53	; Non-initial State, software only.

	dc.b 241	; Non-initial State, software only.
	dc.b 246	; New LSB for software period.
	dc.b 2	; New MSB for software period, maybe with noise.

	dc.b 49	; Non-initial State, software only.


Subsong0_RegisterBlock_34:
	dc.b 105	; Initial State: software only.
	dc.b 63, 1	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_38 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_43:
	dc.b 73	; Initial State: software only.
	dc.b 124, 0	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 247	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 244	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 241	; New LSB for software period.


Subsong0_RegisterBlock_78:
	dc.b 73	; Initial State: software only.
	dc.b 134, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_118 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_83:
	dc.b 89	; Initial State: software only.
	dc.b 251, 0	; Software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 249	; New LSB for software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 251	; New LSB for software period.

	dc.b 101	; Non-initial State, software only.
	dc.b 253	; New LSB for software period.


Subsong0_RegisterBlock_88:
	dc.b 73	; Initial State: software only.
	dc.b 179, 0	; Software period.

	dc.b 8
	dc.w Subsong0_RegisterBlock_148 + 3 - Subsong0	; Optimization: goto common Block at index 1.

Subsong0_RegisterBlock_92:
	dc.b 73	; Initial State: software only.
	dc.b 166, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 76	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 109	; Non-initial State, software only.
	dc.b 73	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 70	; New LSB for software period.


Subsong0_RegisterBlock_120:
	dc.b 73	; Initial State: software only.
	dc.b 130, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 4	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 109	; Non-initial State, software only.
	dc.b 0	; New LSB for software period.

	dc.b 237	; Non-initial State, software only.
	dc.b 252	; New LSB for software period.
	dc.b 0	; New MSB for software period, maybe with noise.


Subsong0_RegisterBlock_145:
	dc.b 73	; Initial State: software only.
	dc.b 147, 0	; Software period.

	dc.b 233	; Non-initial State, software only.
	dc.b 39	; New LSB for software period.
	dc.b 1	; New MSB for software period, maybe with noise.

	dc.b 109	; Non-initial State, software only.
	dc.b 36	; New LSB for software period.

	dc.b 109	; Non-initial State, software only.
	dc.b 33	; New LSB for software period.


Subsong0_RegisterBlock_153:
	dc.b 73	; Initial State: software only.
	dc.b 119, 0	; Software period.

	dc.b 105	; Non-initial State, software only.
	dc.b 239	; New LSB for software period.

	dc.b 45	; Non-initial State, software only.

	dc.b 45	; Non-initial State, software only.


