; Song Empty in Lightweight format.
; Generated by Arkos Tracker 2.

Empty_SongStart
        db "ATLW"       ; Format marker (LightWeight).
        db 0    ; Format version.
        dw Empty_FmInstrumentTable
        dw Empty_ArpeggioTable
        dw Empty_PitchTable
; Table of the Subsongs.
        dw Empty_Subsong1

; The Arpeggio table.
Empty_ArpeggioTable
        dw 0

; The Pitch table.
Empty_PitchTable
        dw 0

; The FM Instrument table.
Empty_FmInstrumentTable
        dw Empty_FmInstrument0
        dw Empty_FmInstrument1

Empty_FmInstrument0
        db 255  ; Speed.

Empty_FmInstrument0_Loop        db 0    ; Volume: 0.

        db 4    ; End the instrument.
        dw Empty_FmInstrument0_Loop     ; Loops.

Empty_FmInstrument1
        db 0    ; Speed.

        db 61   ; Volume: 15.

        db 57   ; Volume: 14.

        db 53   ; Volume: 13.

        db 49   ; Volume: 12.

        db 45   ; Volume: 11.

        db 41   ; Volume: 10.

        db 37   ; Volume: 9.

        db 33   ; Volume: 8.

        db 29   ; Volume: 7.

        db 25   ; Volume: 6.

        db 21   ; Volume: 5.

        db 17   ; Volume: 4.

        db 13   ; Volume: 3.

        db 9    ; Volume: 2.

        db 5    ; Volume: 1.

        db 4    ; End the instrument.
        dw Empty_FmInstrument0_Loop     ; Loop to silence.

; Song Empty, Subsong 1 - Main - in Lightweight format.
; Generated by Arkos Tracker 2.

Empty_Subsong1
; The Linker.
; Pattern 0
Empty_Subsong1_Loop
        db 15   ; State byte.
        db 6    ; New speed.
        db 63   ; New height.
        db 0, 0, 0      ; The transpositions.
        dw Empty_Subsong1_Track0, Empty_Subsong1_Track1, Empty_Subsong1_Track2  ; The tracks.

        db 0    ; End of the subsong.
        dw Empty_Subsong1_Loop

; The Tracks.
Empty_Subsong1_Track0
        db 61, 63       ; Long wait: 64.


Empty_Subsong1_Track1
        db 61, 63       ; Long wait: 64.


Empty_Subsong1_Track2
        db 61, 63       ; Long wait: 64.


