; Song Untitled in Lightweight format.
; Generated by Arkos Tracker 2.

Untitled_SongStart
        db "ATLW"       ; Format marker (LightWeight).
        db 0    ; Format version.
        dw Untitled_FmInstrumentTable
        dw Untitled_ArpeggioTable
        dw Untitled_PitchTable
; Table of the Subsongs.
        dw Untitled_Subsong1

; The Arpeggio table.
Untitled_ArpeggioTable
        dw 0

; The Pitch table.
Untitled_PitchTable
        dw 0

; The FM Instrument table.
Untitled_FmInstrumentTable
        dw Untitled_FmInstrument0
        dw Untitled_FmInstrument1
        dw Untitled_FmInstrument2
        dw Untitled_FmInstrument3
        dw Untitled_FmInstrument4
        dw Untitled_FmInstrument5
        dw Untitled_FmInstrument6
        dw Untitled_FmInstrument7
        dw Untitled_FmInstrument8
        dw Untitled_FmInstrument9
        dw Untitled_FmInstrument10
        dw Untitled_FmInstrument11
        dw Untitled_FmInstrument12
        dw Untitled_FmInstrument13
        dw Untitled_FmInstrument14
        dw Untitled_FmInstrument15
        dw Untitled_FmInstrument16
        dw Untitled_FmInstrument17
        dw Untitled_FmInstrument18

Untitled_FmInstrument0
        db 255  ; Speed.

Untitled_FmInstrument0_Loop     db 0    ; Volume: 0.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument0_Loop  ; Loops.

Untitled_FmInstrument1
        db 0    ; Speed.

        db 189  ; Volume: 15.
        db 1    ; Arpeggio: 0.
        db 1    ; Noise: 1.

        db 185  ; Volume: 14.
        db 24   ; Arpeggio: 12.

Untitled_FmInstrument1_Loop     db 53   ; Volume: 13.

        db 181  ; Volume: 13.
        db 24   ; Arpeggio: 12.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument1_Loop  ; Loops.

Untitled_FmInstrument2
        db 0    ; Speed.

        db 189  ; Volume: 15.
        db 24   ; Arpeggio: 12.

        db 61   ; Volume: 15.

        db 185  ; Volume: 14.
        db 24   ; Arpeggio: 12.

        db 181  ; Volume: 13.
        db 232  ; Arpeggio: -12.

        db 173  ; Volume: 11.
        db 48   ; Arpeggio: 24.

Untitled_FmInstrument2_Loop     db 41   ; Volume: 10.

        db 169  ; Volume: 10.
        db 24   ; Arpeggio: 12.

        db 169  ; Volume: 10.
        db 232  ; Arpeggio: -12.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument2_Loop  ; Loops.

Untitled_FmInstrument3
        db 0    ; Speed.

        db 189  ; Volume: 15.
        db 49   ; Arpeggio: 24.
        db 1    ; Noise: 1.

        db 232  ; Volume: 13.
        db 6    ; Noise.

        db 216  ; Volume: 11.
        db 8    ; Noise.

Untitled_FmInstrument3_Loop     db 181  ; Volume: 13.
        db 24   ; Arpeggio: 12.

        db 53   ; Volume: 13.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument3_Loop  ; Loops.

Untitled_FmInstrument4
        db 0    ; Speed.

        db 248  ; Volume: 15.
        db 1    ; Noise.

        db 232  ; Volume: 13.
        db 6    ; Noise.

        db 216  ; Volume: 11.
        db 8    ; Noise.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument0_Loop  ; Loop to silence.

Untitled_FmInstrument5
        db 0    ; Speed.

        db 189  ; Volume: 15.
        db 24   ; Arpeggio: 12.

        db 185  ; Volume: 14.
        db 24   ; Arpeggio: 12.

        db 53   ; Volume: 13.

        db 177  ; Volume: 12.
        db 24   ; Arpeggio: 12.

        db 45   ; Volume: 11.

        db 169  ; Volume: 10.
        db 24   ; Arpeggio: 12.

        db 37   ; Volume: 9.

        db 161  ; Volume: 8.
        db 24   ; Arpeggio: 12.

        db 29   ; Volume: 7.

        db 153  ; Volume: 6.
        db 24   ; Arpeggio: 12.

        db 21   ; Volume: 5.

        db 145  ; Volume: 4.
        db 24   ; Arpeggio: 12.

        db 13   ; Volume: 3.

        db 137  ; Volume: 2.
        db 24   ; Arpeggio: 12.

        db 5    ; Volume: 1.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument0_Loop  ; Loop to silence.

Untitled_FmInstrument6
        db 0    ; Speed.

        db 189  ; Volume: 15.
        db 24   ; Arpeggio: 12.

        db 57   ; Volume: 14.

        db 53   ; Volume: 13.

        db 49   ; Volume: 12.

Untitled_FmInstrument6_Loop     db 173  ; Volume: 11.
        db 24   ; Arpeggio: 12.

        db 45   ; Volume: 11.

        db 41   ; Volume: 10.

        db 45   ; Volume: 11.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument6_Loop  ; Loops.

Untitled_FmInstrument7
        db 0    ; Speed.

        db 189  ; Volume: 15.
        db 24   ; Arpeggio: 12.

        db 189  ; Volume: 15.
        db 246  ; Arpeggio: -5.

        db 57   ; Volume: 14.

        db 53   ; Volume: 13.

        db 177  ; Volume: 12.
        db 232  ; Arpeggio: -12.

        db 45   ; Volume: 11.

        db 41   ; Volume: 10.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument0_Loop  ; Loop to silence.

Untitled_FmInstrument8
        db 0    ; Speed.

        db 61   ; Volume: 15.

        db 185  ; Volume: 14.
        db 24   ; Arpeggio: 12.

Untitled_FmInstrument8_Loop     db 53   ; Volume: 13.

        db 181  ; Volume: 13.
        db 24   ; Arpeggio: 12.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument8_Loop  ; Loops.

Untitled_FmInstrument9
        db 0    ; Speed.

        db 57   ; Volume: 14.

        db 173  ; Volume: 11.
        db 8    ; Arpeggio: 4.

        db 173  ; Volume: 11.
        db 14   ; Arpeggio: 7.

        db 41   ; Volume: 10.

        db 169  ; Volume: 10.
        db 8    ; Arpeggio: 4.

        db 169  ; Volume: 10.
        db 14   ; Arpeggio: 7.

        db 41   ; Volume: 10.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument0_Loop  ; Loop to silence.

Untitled_FmInstrument10
        db 0    ; Speed.

        db 57   ; Volume: 14.

        db 177  ; Volume: 12.
        db 8    ; Arpeggio: 4.

        db 173  ; Volume: 11.
        db 12   ; Arpeggio: 6.

        db 41   ; Volume: 10.

        db 169  ; Volume: 10.
        db 8    ; Arpeggio: 4.

        db 169  ; Volume: 10.
        db 12   ; Arpeggio: 6.

        db 41   ; Volume: 10.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument0_Loop  ; Loop to silence.

Untitled_FmInstrument11
        db 0    ; Speed.

Untitled_FmInstrument11_Loop    db 61   ; Volume: 15.

        db 189  ; Volume: 15.
        db 24   ; Arpeggio: 12.

        db 189  ; Volume: 15.
        db 250  ; Arpeggio: -3.

        db 189  ; Volume: 15.
        db 18   ; Arpeggio: 9.

        db 189  ; Volume: 15.
        db 242  ; Arpeggio: -7.

        db 189  ; Volume: 15.
        db 10   ; Arpeggio: 5.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument11_Loop ; Loops.

Untitled_FmInstrument12
        db 0    ; Speed.

Untitled_FmInstrument12_Loop    db 189  ; Volume: 15.
        db 254  ; Arpeggio: -1.

        db 189  ; Volume: 15.
        db 22   ; Arpeggio: 11.

        db 189  ; Volume: 15.
        db 250  ; Arpeggio: -3.

        db 189  ; Volume: 15.
        db 18   ; Arpeggio: 9.

        db 189  ; Volume: 15.
        db 242  ; Arpeggio: -7.

        db 189  ; Volume: 15.
        db 10   ; Arpeggio: 5.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument12_Loop ; Loops.

Untitled_FmInstrument13
        db 0    ; Speed.

        db 61   ; Volume: 15.

        db 61   ; Volume: 15.

        db 45   ; Volume: 11.

        db 45   ; Volume: 11.

        db 57   ; Volume: 14.

        db 57   ; Volume: 14.

Untitled_FmInstrument13_Loop    db 41   ; Volume: 10.

        db 41   ; Volume: 10.

        db 53   ; Volume: 13.

        db 53   ; Volume: 13.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument13_Loop ; Loops.

Untitled_FmInstrument14
        db 0    ; Speed.

        db 57   ; Volume: 14.

        db 173  ; Volume: 11.
        db 14   ; Arpeggio: 7.

        db 173  ; Volume: 11.
        db 20   ; Arpeggio: 10.

        db 41   ; Volume: 10.

        db 169  ; Volume: 10.
        db 14   ; Arpeggio: 7.

        db 169  ; Volume: 10.
        db 20   ; Arpeggio: 10.

        db 41   ; Volume: 10.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument0_Loop  ; Loop to silence.

Untitled_FmInstrument15
        db 0    ; Speed.

        db 61   ; Volume: 15.

        db 173  ; Volume: 11.
        db 14   ; Arpeggio: 7.

        db 173  ; Volume: 11.
        db 18   ; Arpeggio: 9.

        db 41   ; Volume: 10.

        db 169  ; Volume: 10.
        db 14   ; Arpeggio: 7.

        db 169  ; Volume: 10.
        db 18   ; Arpeggio: 9.

        db 41   ; Volume: 10.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument0_Loop  ; Loop to silence.

Untitled_FmInstrument16
        db 0    ; Speed.

        db 185  ; Volume: 14.
        db 8    ; Arpeggio: 4.

        db 185  ; Volume: 14.
        db 14   ; Arpeggio: 7.

        db 185  ; Volume: 14.
        db 18   ; Arpeggio: 9.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument0_Loop  ; Loop to silence.

Untitled_FmInstrument17
        db 0    ; Speed.

        db 185  ; Volume: 14.
        db 8    ; Arpeggio: 4.

        db 185  ; Volume: 14.
        db 14   ; Arpeggio: 7.

        db 185  ; Volume: 14.
        db 18   ; Arpeggio: 9.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument0_Loop  ; Loop to silence.

Untitled_FmInstrument18
        db 0    ; Speed.

Untitled_FmInstrument18_Loop    db 57   ; Volume: 14.

        db 9    ; Volume: 2.

        db 4    ; End the instrument.
        dw Untitled_FmInstrument18_Loop ; Loops.

; Song Untitled, Subsong 1 - Main - in Lightweight format.
; Generated by Arkos Tracker 2.

Untitled_Subsong1
; The Linker.
; Pattern 0
Untitled_Subsong1_Loop
        db 15   ; State byte.
        db 3    ; New speed.
        db 5    ; New height.
        db 0, 0, 0      ; The transpositions.
        dw Untitled_Subsong1_Track5, Untitled_Subsong1_Track1, Untitled_Subsong1_Track6 ; The tracks.

; Pattern 1
        db 5    ; State byte.
        db 23   ; New height.
        dw Untitled_Subsong1_Track0, Untitled_Subsong1_Track1, Untitled_Subsong1_Track7 ; The tracks.

; Pattern 2
        db 1    ; State byte.
        dw Untitled_Subsong1_Track0, Untitled_Subsong1_Track1, Untitled_Subsong1_Track7 ; The tracks.

; Pattern 3
        db 1    ; State byte.
        dw Untitled_Subsong1_Track0, Untitled_Subsong1_Track1, Untitled_Subsong1_Track7 ; The tracks.

; Pattern 4
        db 5    ; State byte.
        db 17   ; New height.
        dw Untitled_Subsong1_Track0, Untitled_Subsong1_Track1, Untitled_Subsong1_Track7 ; The tracks.

; Pattern 5
        db 5    ; State byte.
        db 5    ; New height.
        dw Untitled_Subsong1_Track5, Untitled_Subsong1_Track1, Untitled_Subsong1_Track6 ; The tracks.

; Pattern 6
        db 5    ; State byte.
        db 47   ; New height.
        dw Untitled_Subsong1_Track8, Untitled_Subsong1_Track1, Untitled_Subsong1_Track2 ; The tracks.

; Pattern 7
        db 1    ; State byte.
        dw Untitled_Subsong1_Track9, Untitled_Subsong1_Track1, Untitled_Subsong1_Track2 ; The tracks.

; Pattern 8
        db 5    ; State byte.
        db 41   ; New height.
        dw Untitled_Subsong1_Track9, Untitled_Subsong1_Track1, Untitled_Subsong1_Track2 ; The tracks.

; Pattern 9
        db 13   ; State byte.
        db 5    ; New height.
        db -4, 1, -4    ; The transpositions.
        dw Untitled_Subsong1_Track17, Untitled_Subsong1_Track1, Untitled_Subsong1_Track14       ; The tracks.

; Pattern 10
        db 13   ; State byte.
        db 47   ; New height.
        db -4, -4, -4   ; The transpositions.
        dw Untitled_Subsong1_Track19, Untitled_Subsong1_Track1, Untitled_Subsong1_Track21       ; The tracks.

; Pattern 11
        db 1    ; State byte.
        dw Untitled_Subsong1_Track27, Untitled_Subsong1_Track1, Untitled_Subsong1_Track24       ; The tracks.

; Pattern 12
        db 1    ; State byte.
        dw Untitled_Subsong1_Track23, Untitled_Subsong1_Track1, Untitled_Subsong1_Track28       ; The tracks.

; Pattern 13
        db 13   ; State byte.
        db 23   ; New height.
        db -3, 0, -3    ; The transpositions.
        dw Untitled_Subsong1_Track18, Untitled_Subsong1_Track1, Untitled_Subsong1_Track22       ; The tracks.

; Pattern 14
        db 1    ; State byte.
        dw Untitled_Subsong1_Track18, Untitled_Subsong1_Track1, Untitled_Subsong1_Track22       ; The tracks.

; Pattern 15
        db 9    ; State byte.
        db -3, 0, 0     ; The transpositions.
        dw Untitled_Subsong1_Track18, Untitled_Subsong1_Track1, Untitled_Subsong1_Track22       ; The tracks.

; Pattern 16
        db 1    ; State byte.
        dw Untitled_Subsong1_Track18, Untitled_Subsong1_Track1, Untitled_Subsong1_Track22       ; The tracks.

; Pattern 17
        db 9    ; State byte.
        db 0, 0, 0      ; The transpositions.
        dw Untitled_Subsong1_Track25, Untitled_Subsong1_Track1, Untitled_Subsong1_Track26       ; The tracks.

; Pattern 18
        db 1    ; State byte.
        dw Untitled_Subsong1_Track25, Untitled_Subsong1_Track1, Untitled_Subsong1_Track26       ; The tracks.

; Pattern 19
        db 9    ; State byte.
        db 10, 0, -2    ; The transpositions.
        dw Untitled_Subsong1_Track25, Untitled_Subsong1_Track1, Untitled_Subsong1_Track26       ; The tracks.

; Pattern 20
        db 9    ; State byte.
        db -2, 0, -2    ; The transpositions.
        dw Untitled_Subsong1_Track25, Untitled_Subsong1_Track1, Untitled_Subsong1_Track26       ; The tracks.

; Pattern 21
        db 9    ; State byte.
        db 0, 0, 0      ; The transpositions.
        dw Untitled_Subsong1_Track25, Untitled_Subsong1_Track1, Untitled_Subsong1_Track26       ; The tracks.

; Pattern 22
        db 1    ; State byte.
        dw Untitled_Subsong1_Track25, Untitled_Subsong1_Track1, Untitled_Subsong1_Track26       ; The tracks.

; Pattern 23
        db 9    ; State byte.
        db 10, 0, -2    ; The transpositions.
        dw Untitled_Subsong1_Track25, Untitled_Subsong1_Track1, Untitled_Subsong1_Track29       ; The tracks.

; Pattern 24
        db 5    ; State byte.
        db 18   ; New height.
        dw Untitled_Subsong1_Track25, Untitled_Subsong1_Track1, Untitled_Subsong1_Track29       ; The tracks.

; Pattern 25
        db 13   ; State byte.
        db 4    ; New height.
        db 0, 0, 0      ; The transpositions.
        dw Untitled_Subsong1_Track30, Untitled_Subsong1_Track1, Untitled_Subsong1_Track30       ; The tracks.

; Pattern 26
        db 13   ; State byte.
        db 11   ; New height.
        db 2, 0, 2      ; The transpositions.
        dw Untitled_Subsong1_Track56, Untitled_Subsong1_Track1, Untitled_Subsong1_Track57       ; The tracks.

; Pattern 27
        db 1    ; State byte.
        dw Untitled_Subsong1_Track56, Untitled_Subsong1_Track1, Untitled_Subsong1_Track57       ; The tracks.

; Pattern 28
        db 5    ; State byte.
        db 23   ; New height.
        dw Untitled_Subsong1_Track56, Untitled_Subsong1_Track1, Untitled_Subsong1_Track57       ; The tracks.

; Pattern 29
        db 1    ; State byte.
        dw Untitled_Subsong1_Track54, Untitled_Subsong1_Track1, Untitled_Subsong1_Track55       ; The tracks.

; Pattern 30
        db 1    ; State byte.
        dw Untitled_Subsong1_Track58, Untitled_Subsong1_Track1, Untitled_Subsong1_Track55       ; The tracks.

; Pattern 31
        db 1    ; State byte.
        dw Untitled_Subsong1_Track54, Untitled_Subsong1_Track1, Untitled_Subsong1_Track55       ; The tracks.

; Pattern 32
        db 1    ; State byte.
        dw Untitled_Subsong1_Track58, Untitled_Subsong1_Track1, Untitled_Subsong1_Track55       ; The tracks.

; Pattern 33
        db 9    ; State byte.
        db 0, 0, 0      ; The transpositions.
        dw Untitled_Subsong1_Track38, Untitled_Subsong1_Track1, Untitled_Subsong1_Track32       ; The tracks.

; Pattern 34
        db 1    ; State byte.
        dw Untitled_Subsong1_Track37, Untitled_Subsong1_Track1, Untitled_Subsong1_Track33       ; The tracks.

; Pattern 35
        db 1    ; State byte.
        dw Untitled_Subsong1_Track51, Untitled_Subsong1_Track1, Untitled_Subsong1_Track53       ; The tracks.

; Pattern 36
        db 1    ; State byte.
        dw Untitled_Subsong1_Track52, Untitled_Subsong1_Track1, Untitled_Subsong1_Track49       ; The tracks.

; Pattern 37
        db 1    ; State byte.
        dw Untitled_Subsong1_Track38, Untitled_Subsong1_Track1, Untitled_Subsong1_Track32       ; The tracks.

; Pattern 38
        db 1    ; State byte.
        dw Untitled_Subsong1_Track37, Untitled_Subsong1_Track1, Untitled_Subsong1_Track33       ; The tracks.

; Pattern 39
        db 9    ; State byte.
        db 3, 0, 0      ; The transpositions.
        dw Untitled_Subsong1_Track37, Untitled_Subsong1_Track1, Untitled_Subsong1_Track32       ; The tracks.

; Pattern 40
        db 9    ; State byte.
        db 6, 0, 0      ; The transpositions.
        dw Untitled_Subsong1_Track38, Untitled_Subsong1_Track1, Untitled_Subsong1_Track36       ; The tracks.

; Pattern 41
        db 9    ; State byte.
        db 0, 0, 0      ; The transpositions.
        dw Untitled_Subsong1_Track39, Untitled_Subsong1_Track1, Untitled_Subsong1_Track36       ; The tracks.

; Pattern 42
        db 9    ; State byte.
        db -2, 0, 0     ; The transpositions.
        dw Untitled_Subsong1_Track39, Untitled_Subsong1_Track1, Untitled_Subsong1_Track36       ; The tracks.

; Pattern 43
        db 9    ; State byte.
        db -4, 0, 0     ; The transpositions.
        dw Untitled_Subsong1_Track40, Untitled_Subsong1_Track1, Untitled_Subsong1_Track36       ; The tracks.

; Pattern 44
        db 9    ; State byte.
        db -2, 0, 0     ; The transpositions.
        dw Untitled_Subsong1_Track18, Untitled_Subsong1_Track1, Untitled_Subsong1_Track45       ; The tracks.

; Pattern 45
        db 5    ; State byte.
        db 17   ; New height.
        dw Untitled_Subsong1_Track18, Untitled_Subsong1_Track1, Untitled_Subsong1_Track45       ; The tracks.

; Pattern 46
        db 13   ; State byte.
        db 5    ; New height.
        db -2, 0, -2    ; The transpositions.
        dw Untitled_Subsong1_Track41, Untitled_Subsong1_Track1, Untitled_Subsong1_Track42       ; The tracks.

; Pattern 47
        db 13   ; State byte.
        db 23   ; New height.
        db 0, 0, 0      ; The transpositions.
        dw Untitled_Subsong1_Track56, Untitled_Subsong1_Track1, Untitled_Subsong1_Track57       ; The tracks.

; Pattern 48
        db 5    ; State byte.
        db 18   ; New height.
        dw Untitled_Subsong1_Track56, Untitled_Subsong1_Track1, Untitled_Subsong1_Track57       ; The tracks.

; Pattern 49
        db 5    ; State byte.
        db 4    ; New height.
        dw Untitled_Subsong1_Track60, Untitled_Subsong1_Track1, Untitled_Subsong1_Track61       ; The tracks.

; Pattern 50
        db 13   ; State byte.
        db 23   ; New height.
        db -2, 0, -2    ; The transpositions.
        dw Untitled_Subsong1_Track18, Untitled_Subsong1_Track1, Untitled_Subsong1_Track22       ; The tracks.

; Pattern 51
        db 5    ; State byte.
        db 17   ; New height.
        dw Untitled_Subsong1_Track18, Untitled_Subsong1_Track1, Untitled_Subsong1_Track22       ; The tracks.

; Pattern 52
        db 5    ; State byte.
        db 5    ; New height.
        dw Untitled_Subsong1_Track41, Untitled_Subsong1_Track1, Untitled_Subsong1_Track42       ; The tracks.

; Pattern 53
        db 1    ; State byte.
        dw Untitled_Subsong1_Track41, Untitled_Subsong1_Track1, Untitled_Subsong1_Track42       ; The tracks.

; Pattern 54
        db 9    ; State byte.
        db 0, 0, 0      ; The transpositions.
        dw Untitled_Subsong1_Track43, Untitled_Subsong1_Track1, Untitled_Subsong1_Track44       ; The tracks.

        db 0    ; End of the subsong.
        dw Untitled_Subsong1_Loop

; The Tracks.
Untitled_Subsong1_Track0
        db 202  ; Note: 34.
        db 16   ; New instrument: 8.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 10   ; Note: 34.
        db 8    ; Note: 32.
        db 10   ; Note: 34.
        db 8    ; Note: 32.
        db 10   ; Note: 34.
        db 62   ; Short wait: 1.

        db 10   ; Note: 34.
        db 8    ; Note: 32.
        db 10   ; Note: 34.
        db 8    ; Note: 32.
        db 10   ; Note: 34.
        db 62   ; Short wait: 1.

        db 10   ; Note: 34.
        db 10   ; Note: 34.
        db 13   ; Note: 37.
        db 15   ; Note: 39.
        db 8    ; Note: 32.
        db 62   ; Short wait: 1.

        db 8    ; Note: 32.
        db 62   ; Short wait: 1.

        db 8    ; Note: 32.
        db 61, 24       ; Long wait: 25.


Untitled_Subsong1_Track1
        db 61, 47       ; Long wait: 48.


Untitled_Subsong1_Track2
        db 233  ; Note: 65.
        db 4    ; New instrument: 2.
        db 129  ; Volume + possible Pitch up/down.
        db 126  ; Short wait: 2.

        db 34   ; Note: 58.
        db 126  ; Short wait: 2.

        db 37   ; Note: 61.
        db 126  ; Short wait: 2.

        db 41   ; Note: 65.
        db 126  ; Short wait: 2.

        db 42   ; Note: 66.
        db 126  ; Short wait: 2.

        db 34   ; Note: 58.
        db 126  ; Short wait: 2.

        db 37   ; Note: 61.
        db 126  ; Short wait: 2.

        db 42   ; Note: 66.
        db 126  ; Short wait: 2.

        db 43   ; Note: 67.
        db 126  ; Short wait: 2.

        db 34   ; Note: 58.
        db 126  ; Short wait: 2.

        db 37   ; Note: 61.
        db 126  ; Short wait: 2.

        db 34   ; Note: 58.
        db 126  ; Short wait: 2.

        db 43   ; Note: 67.
        db 126  ; Short wait: 2.

        db 34   ; Note: 58.
        db 126  ; Short wait: 2.

        db 37   ; Note: 61.
        db 126  ; Short wait: 2.

        db 44   ; Note: 68.
        db 126  ; Short wait: 2.


Untitled_Subsong1_Track5
        db 196  ; Note: 28.
        db 16   ; New instrument: 8.
        db 128  ; Volume + possible Pitch up/down.
        db 5    ; Note: 29.
        db 6    ; Note: 30.
        db 7    ; Note: 31.
        db 8    ; Note: 32.
        db 9    ; Note: 33.
        db 61, 41       ; Long wait: 42.


Untitled_Subsong1_Track6
        db 209  ; Note: 41.
        db 4    ; New instrument: 2.
        db 128  ; Volume + possible Pitch up/down.
        db 18   ; Note: 42.
        db 19   ; Note: 43.
        db 20   ; Note: 44.
        db 21   ; Note: 45.
        db 22   ; Note: 46.
        db 61, 41       ; Long wait: 42.


Untitled_Subsong1_Track7
        db 255, 22      ; Escaped note: 22.
        db 10   ; New instrument: 5.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 63, 22       ; Escaped note: 22.
        db 63, 20       ; Escaped note: 20.
        db 63, 22       ; Escaped note: 22.
        db 63, 20       ; Escaped note: 20.
        db 63, 22       ; Escaped note: 22.
        db 62   ; Short wait: 1.

        db 63, 22       ; Escaped note: 22.
        db 63, 20       ; Escaped note: 20.
        db 63, 22       ; Escaped note: 22.
        db 63, 20       ; Escaped note: 20.
        db 63, 22       ; Escaped note: 22.
        db 62   ; Short wait: 1.

        db 63, 22       ; Escaped note: 22.
        db 63, 22       ; Escaped note: 22.
        db 1    ; Note: 25.
        db 3    ; Note: 27.
        db 63, 20       ; Escaped note: 20.
        db 62   ; Short wait: 1.

        db 63, 20       ; Escaped note: 20.
        db 62   ; Short wait: 1.

        db 63, 20       ; Escaped note: 20.
        db 61, 24       ; Long wait: 25.


Untitled_Subsong1_Track8
        db 191, 22      ; Escaped note: 22.
        db 16   ; New instrument: 8.
        db 126  ; Short wait: 2.

        db 10   ; Note: 34.
        db 126  ; Short wait: 2.

        db 63, 22       ; Escaped note: 22.
        db 63, 22       ; Escaped note: 22.
        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 126  ; Short wait: 2.

        db 63, 18       ; Escaped note: 18.
        db 126  ; Short wait: 2.

        db 6    ; Note: 30.
        db 126  ; Short wait: 2.

        db 63, 18       ; Escaped note: 18.
        db 63, 18       ; Escaped note: 18.
        db 63, 18       ; Escaped note: 18.
        db 6    ; Note: 30.
        db 62   ; Short wait: 1.

        db 6    ; Note: 30.
        db 63, 15       ; Escaped note: 15.
        db 126  ; Short wait: 2.

        db 3    ; Note: 27.
        db 126  ; Short wait: 2.

        db 63, 15       ; Escaped note: 15.
        db 63, 15       ; Escaped note: 15.
        db 63, 15       ; Escaped note: 15.
        db 3    ; Note: 27.
        db 126  ; Short wait: 2.

        db 63, 15       ; Escaped note: 15.
        db 126  ; Short wait: 2.

        db 3    ; Note: 27.
        db 126  ; Short wait: 2.

        db 63, 18       ; Escaped note: 18.
        db 63, 18       ; Escaped note: 18.
        db 6    ; Note: 30.
        db 63, 20       ; Escaped note: 20.
        db 63, 20       ; Escaped note: 20.
        db 8    ; Note: 32.

Untitled_Subsong1_Track9
        db 191, 22      ; Escaped note: 22.
        db 16   ; New instrument: 8.
        db 62   ; Short wait: 1.

        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 126  ; Short wait: 2.

        db 63, 22       ; Escaped note: 22.
        db 62   ; Short wait: 1.

        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 126  ; Short wait: 2.

        db 63, 18       ; Escaped note: 18.
        db 62   ; Short wait: 1.

        db 63, 18       ; Escaped note: 18.
        db 6    ; Note: 30.
        db 126  ; Short wait: 2.

        db 63, 18       ; Escaped note: 18.
        db 62   ; Short wait: 1.

        db 63, 18       ; Escaped note: 18.
        db 6    ; Note: 30.
        db 126  ; Short wait: 2.

        db 3    ; Note: 27.
        db 62   ; Short wait: 1.

        db 3    ; Note: 27.
        db 3    ; Note: 27.
        db 1    ; Note: 25.
        db 63, 22       ; Escaped note: 22.
        db 3    ; Note: 27.
        db 62   ; Short wait: 1.

        db 3    ; Note: 27.
        db 3    ; Note: 27.
        db 1    ; Note: 25.
        db 63, 22       ; Escaped note: 22.
        db 3    ; Note: 27.
        db 62   ; Short wait: 1.

        db 3    ; Note: 27.
        db 3    ; Note: 27.
        db 1    ; Note: 25.
        db 63, 22       ; Escaped note: 22.
        db 63, 18       ; Escaped note: 18.
        db 6    ; Note: 30.
        db 6    ; Note: 30.
        db 63, 20       ; Escaped note: 20.
        db 8    ; Note: 32.
        db 8    ; Note: 32.

Untitled_Subsong1_Track14
        db 169  ; Note: 65.
        db 12   ; New instrument: 6.
        db 40   ; Note: 64.
        db 38   ; Note: 62.
        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.
        db 61, 41       ; Long wait: 42.


Untitled_Subsong1_Track17
        db 138  ; Note: 34.
        db 16   ; New instrument: 8.
        db 10   ; Note: 34.
        db 10   ; Note: 34.
        db 12   ; Note: 36.
        db 14   ; Note: 38.
        db 17   ; Note: 41.
        db 61, 41       ; Long wait: 42.


Untitled_Subsong1_Track18
        db 193  ; Note: 25.
        db 16   ; New instrument: 8.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 63, 23       ; Escaped note: 23.
        db 0    ; Note: 24.
        db 1    ; Note: 25.
        db 62   ; Short wait: 1.

        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 63, 23       ; Escaped note: 23.
        db 0    ; Note: 24.
        db 1    ; Note: 25.
        db 62   ; Short wait: 1.

        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 63, 23       ; Escaped note: 23.
        db 0    ; Note: 24.
        db 1    ; Note: 25.
        db 63, 23       ; Escaped note: 23.
        db 1    ; Note: 25.
        db 63, 23       ; Escaped note: 23.
        db 4    ; Note: 28.
        db 6    ; Note: 30.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track19
        db 138  ; Note: 34.
        db 16   ; New instrument: 8.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 10   ; Note: 34.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 174  ; Note: 70.
        db 18   ; New instrument: 9.
        db 46   ; Note: 70.
        db 46   ; Note: 70.
        db 174  ; Note: 70.
        db 20   ; New instrument: 10.
        db 174  ; Note: 70.
        db 18   ; New instrument: 9.
        db 46   ; Note: 70.
        db 191, 22      ; Escaped note: 22.
        db 16   ; New instrument: 8.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 12   ; Note: 36.
        db 14   ; Note: 38.
        db 17   ; Note: 41.
        db 7    ; Note: 31.
        db 7    ; Note: 31.
        db 19   ; Note: 43.
        db 63, 19       ; Escaped note: 19.
        db 7    ; Note: 31.
        db 19   ; Note: 43.
        db 171  ; Note: 67.
        db 18   ; New instrument: 9.
        db 43   ; Note: 67.
        db 43   ; Note: 67.
        db 171  ; Note: 67.
        db 20   ; New instrument: 10.
        db 171  ; Note: 67.
        db 18   ; New instrument: 9.
        db 43   ; Note: 67.
        db 191, 19      ; Escaped note: 19.
        db 16   ; New instrument: 8.
        db 7    ; Note: 31.
        db 19   ; Note: 43.
        db 63, 19       ; Escaped note: 19.
        db 7    ; Note: 31.
        db 7    ; Note: 31.
        db 17   ; Note: 41.
        db 19   ; Note: 43.
        db 14   ; Note: 38.
        db 17   ; Note: 41.
        db 19   ; Note: 43.
        db 14   ; Note: 38.

Untitled_Subsong1_Track21
        db 162  ; Note: 58.
        db 12   ; New instrument: 6.
        db 61, 16       ; Long wait: 17.

        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.
        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.
        db 35   ; Note: 59.
        db 61, 16       ; Long wait: 17.

        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.
        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.

Untitled_Subsong1_Track22
        db 193  ; Note: 25.
        db 12   ; New instrument: 6.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 63, 23       ; Escaped note: 23.
        db 0    ; Note: 24.
        db 1    ; Note: 25.
        db 62   ; Short wait: 1.

        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 63, 23       ; Escaped note: 23.
        db 0    ; Note: 24.
        db 1    ; Note: 25.
        db 62   ; Short wait: 1.

        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 63, 23       ; Escaped note: 23.
        db 0    ; Note: 24.
        db 1    ; Note: 25.
        db 63, 23       ; Escaped note: 23.
        db 1    ; Note: 25.
        db 63, 23       ; Escaped note: 23.
        db 4    ; Note: 28.
        db 6    ; Note: 30.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track23
        db 138  ; Note: 34.
        db 16   ; New instrument: 8.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 10   ; Note: 34.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 174  ; Note: 70.
        db 18   ; New instrument: 9.
        db 46   ; Note: 70.
        db 46   ; Note: 70.
        db 174  ; Note: 70.
        db 20   ; New instrument: 10.
        db 174  ; Note: 70.
        db 18   ; New instrument: 9.
        db 46   ; Note: 70.
        db 191, 22      ; Escaped note: 22.
        db 16   ; New instrument: 8.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 12   ; Note: 36.
        db 14   ; Note: 38.
        db 17   ; Note: 41.
        db 171  ; Note: 67.
        db 18   ; New instrument: 9.
        db 135  ; Note: 31.
        db 16   ; New instrument: 8.
        db 19   ; Note: 43.
        db 171  ; Note: 67.
        db 18   ; New instrument: 9.
        db 135  ; Note: 31.
        db 16   ; New instrument: 8.
        db 19   ; Note: 43.
        db 171  ; Note: 67.
        db 20   ; New instrument: 10.
        db 135  ; Note: 31.
        db 16   ; New instrument: 8.
        db 19   ; Note: 43.
        db 171  ; Note: 67.
        db 18   ; New instrument: 9.
        db 130  ; Note: 26.
        db 16   ; New instrument: 8.
        db 4    ; Note: 28.
        db 5    ; Note: 29.
        db 126  ; Short wait: 2.

        db 7    ; Note: 31.
        db 126  ; Short wait: 2.

        db 9    ; Note: 33.
        db 126  ; Short wait: 2.

        db 22   ; Note: 46.
        db 24   ; Note: 48.
        db 26   ; Note: 50.

Untitled_Subsong1_Track24
        db 162  ; Note: 58.
        db 12   ; New instrument: 6.
        db 61, 16       ; Long wait: 17.

        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.
        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.
        db 35   ; Note: 59.
        db 61, 16       ; Long wait: 17.

        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.
        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.

Untitled_Subsong1_Track25
        db 195  ; Note: 27.
        db 16   ; New instrument: 8.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 3    ; Note: 27.
        db 3    ; Note: 27.
        db 1    ; Note: 25.
        db 63, 22       ; Escaped note: 22.
        db 3    ; Note: 27.
        db 62   ; Short wait: 1.

        db 3    ; Note: 27.
        db 3    ; Note: 27.
        db 1    ; Note: 25.
        db 63, 22       ; Escaped note: 22.
        db 3    ; Note: 27.
        db 62   ; Short wait: 1.

        db 3    ; Note: 27.
        db 3    ; Note: 27.
        db 1    ; Note: 25.
        db 63, 22       ; Escaped note: 22.
        db 63, 18       ; Escaped note: 18.
        db 6    ; Note: 30.
        db 6    ; Note: 30.
        db 63, 20       ; Escaped note: 20.
        db 8    ; Note: 32.
        db 8    ; Note: 32.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track26
        db 226  ; Note: 58.
        db 22   ; New instrument: 11.
        db 131  ; Volume + possible Pitch up/down.
        db 61, 4        ; Long wait: 5.

        db 219  ; Note: 51.
        db 32   ; New instrument: 16.
        db 128  ; Volume + possible Pitch up/down.
        db 103  ; Note: 63.
        db 129  ; Volume + possible Pitch up/down.
        db 91   ; Note: 51.
        db 130  ; Volume + possible Pitch up/down.
        db 103  ; Note: 63.
        db 131  ; Volume + possible Pitch up/down.
        db 91   ; Note: 51.
        db 132  ; Volume + possible Pitch up/down.
        db 103  ; Note: 63.
        db 133  ; Volume + possible Pitch up/down.
        db 226  ; Note: 58.
        db 24   ; New instrument: 12.
        db 131  ; Volume + possible Pitch up/down.
        db 61, 34       ; Long wait: 35.


Untitled_Subsong1_Track27
        db 138  ; Note: 34.
        db 16   ; New instrument: 8.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 10   ; Note: 34.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 174  ; Note: 70.
        db 18   ; New instrument: 9.
        db 46   ; Note: 70.
        db 46   ; Note: 70.
        db 174  ; Note: 70.
        db 20   ; New instrument: 10.
        db 174  ; Note: 70.
        db 18   ; New instrument: 9.
        db 46   ; Note: 70.
        db 191, 22      ; Escaped note: 22.
        db 16   ; New instrument: 8.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 22   ; Note: 46.
        db 12   ; Note: 36.
        db 14   ; Note: 38.
        db 17   ; Note: 41.
        db 19   ; Note: 43.
        db 62   ; Short wait: 1.

        db 19   ; Note: 43.
        db 62   ; Short wait: 1.

        db 17   ; Note: 41.
        db 14   ; Note: 38.
        db 19   ; Note: 43.
        db 62   ; Short wait: 1.

        db 19   ; Note: 43.
        db 62   ; Short wait: 1.

        db 17   ; Note: 41.
        db 14   ; Note: 38.
        db 7    ; Note: 31.
        db 62   ; Short wait: 1.

        db 7    ; Note: 31.
        db 62   ; Short wait: 1.

        db 5    ; Note: 29.
        db 2    ; Note: 26.
        db 10   ; Note: 34.
        db 12   ; Note: 36.
        db 14   ; Note: 38.
        db 22   ; Note: 46.
        db 24   ; Note: 48.
        db 26   ; Note: 50.

Untitled_Subsong1_Track28
        db 162  ; Note: 58.
        db 12   ; New instrument: 6.
        db 61, 16       ; Long wait: 17.

        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.
        db 41   ; Note: 65.
        db 40   ; Note: 64.
        db 38   ; Note: 62.
        db 35   ; Note: 59.
        db 61, 8        ; Long wait: 9.

        db 63, 14       ; Escaped note: 14.
        db 63, 16       ; Escaped note: 16.
        db 63, 17       ; Escaped note: 17.
        db 126  ; Short wait: 2.

        db 63, 19       ; Escaped note: 19.
        db 126  ; Short wait: 2.

        db 63, 21       ; Escaped note: 21.
        db 126  ; Short wait: 2.

        db 10   ; Note: 34.
        db 12   ; Note: 36.
        db 14   ; Note: 38.

Untitled_Subsong1_Track29
        db 214  ; Note: 46.
        db 12   ; New instrument: 6.
        db 129  ; Volume + possible Pitch up/down.
        db 19   ; Note: 43.
        db 15   ; Note: 39.
        db 22   ; Note: 46.
        db 19   ; Note: 43.
        db 15   ; Note: 39.
        db 22   ; Note: 46.
        db 19   ; Note: 43.
        db 15   ; Note: 39.
        db 22   ; Note: 46.
        db 19   ; Note: 43.
        db 15   ; Note: 39.
        db 21   ; Note: 45.
        db 19   ; Note: 43.
        db 15   ; Note: 39.
        db 21   ; Note: 45.
        db 19   ; Note: 43.
        db 15   ; Note: 39.
        db 21   ; Note: 45.
        db 19   ; Note: 43.
        db 15   ; Note: 39.
        db 21   ; Note: 45.
        db 19   ; Note: 43.
        db 15   ; Note: 39.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track30
        db 60   ; No note, effects only.
        db 145  ; Volume + possible Pitch up/down.
        dw 512  ; Pitch.
        db 60   ; No note, effects only.
        db 146  ; Volume + possible Pitch up/down.
        dw 512  ; Pitch.
        db 60   ; No note, effects only.
        db 147  ; Volume + possible Pitch up/down.
        dw 512  ; Pitch.
        db 60   ; No note, effects only.
        db 148  ; Volume + possible Pitch up/down.
        dw 512  ; Pitch.
        db 60   ; No note, effects only.
        db 149  ; Volume + possible Pitch up/down.
        dw 512  ; Pitch.
        db 60   ; No note, effects only.
        db 150  ; Volume + possible Pitch up/down.
        dw 512  ; Pitch.
        db 60   ; No note, effects only.
        db 151  ; Volume + possible Pitch up/down.
        dw 512  ; Pitch.
        db 60   ; No note, effects only.
        db 152  ; Volume + possible Pitch up/down.
        dw 512  ; Pitch.
        db 60   ; No note, effects only.
        db 128  ; Volume + possible Pitch up/down.
        db 61, 38       ; Long wait: 39.


Untitled_Subsong1_Track32
        db 217  ; Note: 49.
        db 12   ; New instrument: 6.
        db 131  ; Volume + possible Pitch up/down.
        db 89   ; Note: 49.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 101  ; Note: 61.
        db 131  ; Volume + possible Pitch up/down.
        db 101  ; Note: 61.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 104  ; Note: 64.
        db 131  ; Volume + possible Pitch up/down.
        db 104  ; Note: 64.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 111  ; Note: 71.
        db 131  ; Volume + possible Pitch up/down.
        db 111  ; Note: 71.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 110  ; Note: 70.
        db 131  ; Volume + possible Pitch up/down.
        db 110  ; Note: 70.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 106  ; Note: 66.
        db 131  ; Volume + possible Pitch up/down.
        db 106  ; Note: 66.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 127, 73      ; Escaped note: 73.
        db 131  ; Volume + possible Pitch up/down.
        db 127, 73      ; Escaped note: 73.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 110  ; Note: 70.
        db 131  ; Volume + possible Pitch up/down.
        db 110  ; Note: 70.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 89   ; Note: 49.
        db 130  ; Volume + possible Pitch up/down.
        db 89   ; Note: 49.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 101  ; Note: 61.
        db 130  ; Volume + possible Pitch up/down.
        db 101  ; Note: 61.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 104  ; Note: 64.
        db 130  ; Volume + possible Pitch up/down.
        db 104  ; Note: 64.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 111  ; Note: 71.
        db 130  ; Volume + possible Pitch up/down.
        db 111  ; Note: 71.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 110  ; Note: 70.
        db 130  ; Volume + possible Pitch up/down.
        db 110  ; Note: 70.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 106  ; Note: 66.
        db 130  ; Volume + possible Pitch up/down.
        db 106  ; Note: 66.
        db 128  ; Volume + possible Pitch up/down.
        db 61, 6        ; Long wait: 7.


Untitled_Subsong1_Track33
        db 217  ; Note: 49.
        db 12   ; New instrument: 6.
        db 131  ; Volume + possible Pitch up/down.
        db 89   ; Note: 49.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 101  ; Note: 61.
        db 131  ; Volume + possible Pitch up/down.
        db 101  ; Note: 61.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 104  ; Note: 64.
        db 131  ; Volume + possible Pitch up/down.
        db 104  ; Note: 64.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 111  ; Note: 71.
        db 131  ; Volume + possible Pitch up/down.
        db 111  ; Note: 71.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 110  ; Note: 70.
        db 131  ; Volume + possible Pitch up/down.
        db 110  ; Note: 70.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 106  ; Note: 66.
        db 131  ; Volume + possible Pitch up/down.
        db 106  ; Note: 66.
        db 129  ; Volume + possible Pitch up/down.
        db 61, 30       ; Long wait: 31.


Untitled_Subsong1_Track36
        db 218  ; Note: 50.
        db 12   ; New instrument: 6.
        db 131  ; Volume + possible Pitch up/down.
        db 90   ; Note: 50.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 102  ; Note: 62.
        db 131  ; Volume + possible Pitch up/down.
        db 102  ; Note: 62.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 106  ; Note: 66.
        db 131  ; Volume + possible Pitch up/down.
        db 106  ; Note: 66.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 111  ; Note: 71.
        db 131  ; Volume + possible Pitch up/down.
        db 111  ; Note: 71.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 127, 73      ; Escaped note: 73.
        db 131  ; Volume + possible Pitch up/down.
        db 127, 73      ; Escaped note: 73.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 127, 74      ; Escaped note: 74.
        db 131  ; Volume + possible Pitch up/down.
        db 127, 74      ; Escaped note: 74.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 127, 76      ; Escaped note: 76.
        db 131  ; Volume + possible Pitch up/down.
        db 127, 76      ; Escaped note: 76.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 127, 78      ; Escaped note: 78.
        db 131  ; Volume + possible Pitch up/down.
        db 127, 78      ; Escaped note: 78.
        db 129  ; Volume + possible Pitch up/down.
        db 61, 24       ; Long wait: 25.


Untitled_Subsong1_Track37
        db 141  ; Note: 37.
        db 16   ; New instrument: 8.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 15   ; Note: 39.
        db 3    ; Note: 27.
        db 15   ; Note: 39.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track38
        db 205  ; Note: 37.
        db 16   ; New instrument: 8.
        db 128  ; Volume + possible Pitch up/down.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 13   ; Note: 37.
        db 1    ; Note: 25.
        db 1    ; Note: 25.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track39
        db 139  ; Note: 35.
        db 16   ; New instrument: 8.
        db 11   ; Note: 35.
        db 11   ; Note: 35.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 11   ; Note: 35.
        db 11   ; Note: 35.
        db 11   ; Note: 35.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 11   ; Note: 35.
        db 10   ; Note: 34.
        db 10   ; Note: 34.
        db 10   ; Note: 34.
        db 63, 22       ; Escaped note: 22.
        db 63, 22       ; Escaped note: 22.
        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 10   ; Note: 34.
        db 10   ; Note: 34.
        db 63, 22       ; Escaped note: 22.
        db 63, 22       ; Escaped note: 22.
        db 10   ; Note: 34.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track40
        db 139  ; Note: 35.
        db 16   ; New instrument: 8.
        db 11   ; Note: 35.
        db 11   ; Note: 35.
        db 63, 23       ; Escaped note: 23.
        db 62   ; Short wait: 1.

        db 152  ; Note: 48.
        db 0    ; New instrument: 0.
        db 139  ; Note: 35.
        db 16   ; New instrument: 8.
        db 11   ; Note: 35.
        db 11   ; Note: 35.
        db 63, 23       ; Escaped note: 23.
        db 62   ; Short wait: 1.

        db 152  ; Note: 48.
        db 0    ; New instrument: 0.
        db 138  ; Note: 34.
        db 16   ; New instrument: 8.
        db 10   ; Note: 34.
        db 63, 22       ; Escaped note: 22.
        db 63, 22       ; Escaped note: 22.
        db 62   ; Short wait: 1.

        db 152  ; Note: 48.
        db 0    ; New instrument: 0.
        db 134  ; Note: 30.
        db 16   ; New instrument: 8.
        db 126  ; Short wait: 2.

        db 5    ; Note: 29.
        db 61, 25       ; Long wait: 26.


Untitled_Subsong1_Track41
        db 191, 21      ; Escaped note: 21.
        db 16   ; New instrument: 8.
        db 9    ; Note: 33.
        db 9    ; Note: 33.
        db 63, 23       ; Escaped note: 23.
        db 11   ; Note: 35.
        db 11   ; Note: 35.
        db 61, 41       ; Long wait: 42.


Untitled_Subsong1_Track42
        db 137  ; Note: 33.
        db 12   ; New instrument: 6.
        db 21   ; Note: 45.
        db 21   ; Note: 45.
        db 11   ; Note: 35.
        db 23   ; Note: 47.
        db 23   ; Note: 47.
        db 61, 41       ; Long wait: 42.


Untitled_Subsong1_Track43
        db 255, 23      ; Escaped note: 23.
        db 16   ; New instrument: 8.
        db 128  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 129  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 130  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 131  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 132  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 133  ; Volume + possible Pitch up/down.
        db 61, 41       ; Long wait: 42.


Untitled_Subsong1_Track44
        db 255, 23      ; Escaped note: 23.
        db 12   ; New instrument: 6.
        db 128  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 129  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 130  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 131  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 132  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 133  ; Volume + possible Pitch up/down.
        db 61, 41       ; Long wait: 42.


Untitled_Subsong1_Track45
        db 60   ; No note, effects only.
        db 146  ; Volume + possible Pitch up/down.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 60   ; No note, effects only.
        db 127  ; Pitch down: 128.
        dw 128  ; Pitch.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track49
        db 215  ; Note: 47.
        db 12   ; New instrument: 6.
        db 131  ; Volume + possible Pitch up/down.
        db 87   ; Note: 47.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 99   ; Note: 59.
        db 131  ; Volume + possible Pitch up/down.
        db 99   ; Note: 59.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 102  ; Note: 62.
        db 131  ; Volume + possible Pitch up/down.
        db 102  ; Note: 62.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 42   ; Note: 66.
        db 106  ; Note: 66.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 105  ; Note: 65.
        db 131  ; Volume + possible Pitch up/down.
        db 105  ; Note: 65.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 101  ; Note: 61.
        db 131  ; Volume + possible Pitch up/down.
        db 101  ; Note: 61.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 236  ; Note: 68.
        db 16   ; New instrument: 8.
        db 131  ; Volume + possible Pitch up/down.
        db 109  ; Note: 69.
        db 130  ; Volume + possible Pitch up/down.
        db 108  ; Note: 68.
        db 129  ; Volume + possible Pitch up/down.
        db 109  ; Note: 69.
        db 131  ; Volume + possible Pitch up/down.
        db 108  ; Note: 68.
        db 132  ; Volume + possible Pitch up/down.
        db 109  ; Note: 69.
        db 133  ; Volume + possible Pitch up/down.
        db 217  ; Note: 49.
        db 12   ; New instrument: 6.
        db 130  ; Volume + possible Pitch up/down.
        db 89   ; Note: 49.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 101  ; Note: 61.
        db 130  ; Volume + possible Pitch up/down.
        db 101  ; Note: 61.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 104  ; Note: 64.
        db 130  ; Volume + possible Pitch up/down.
        db 104  ; Note: 64.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 111  ; Note: 71.
        db 130  ; Volume + possible Pitch up/down.
        db 111  ; Note: 71.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 110  ; Note: 70.
        db 130  ; Volume + possible Pitch up/down.
        db 110  ; Note: 70.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 106  ; Note: 66.
        db 130  ; Volume + possible Pitch up/down.
        db 106  ; Note: 66.
        db 128  ; Volume + possible Pitch up/down.
        db 61, 6        ; Long wait: 7.


Untitled_Subsong1_Track51
        db 144  ; Note: 40.
        db 16   ; New instrument: 8.
        db 4    ; Note: 28.
        db 4    ; Note: 28.
        db 16   ; Note: 40.
        db 4    ; Note: 28.
        db 4    ; Note: 28.
        db 16   ; Note: 40.
        db 4    ; Note: 28.
        db 4    ; Note: 28.
        db 16   ; Note: 40.
        db 4    ; Note: 28.
        db 16   ; Note: 40.
        db 16   ; Note: 40.
        db 4    ; Note: 28.
        db 4    ; Note: 28.
        db 16   ; Note: 40.
        db 4    ; Note: 28.
        db 4    ; Note: 28.
        db 16   ; Note: 40.
        db 4    ; Note: 28.
        db 4    ; Note: 28.
        db 4    ; Note: 28.
        db 4    ; Note: 28.
        db 4    ; Note: 28.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track52
        db 203  ; Note: 35.
        db 16   ; New instrument: 8.
        db 128  ; Volume + possible Pitch up/down.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 11   ; Note: 35.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 11   ; Note: 35.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 11   ; Note: 35.
        db 63, 23       ; Escaped note: 23.
        db 11   ; Note: 35.
        db 11   ; Note: 35.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 11   ; Note: 35.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 5    ; Note: 29.
        db 5    ; Note: 29.
        db 5    ; Note: 29.
        db 8    ; Note: 32.
        db 62   ; Short wait: 1.

        db 60   ; No note, effects only.
        db 143  ; Volume + possible Pitch up/down.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track53
        db 217  ; Note: 49.
        db 12   ; New instrument: 6.
        db 131  ; Volume + possible Pitch up/down.
        db 89   ; Note: 49.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 101  ; Note: 61.
        db 131  ; Volume + possible Pitch up/down.
        db 101  ; Note: 61.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 104  ; Note: 64.
        db 131  ; Volume + possible Pitch up/down.
        db 104  ; Note: 64.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 111  ; Note: 71.
        db 131  ; Volume + possible Pitch up/down.
        db 111  ; Note: 71.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 110  ; Note: 70.
        db 131  ; Volume + possible Pitch up/down.
        db 110  ; Note: 70.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 106  ; Note: 66.
        db 131  ; Volume + possible Pitch up/down.
        db 106  ; Note: 66.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 127, 73      ; Escaped note: 73.
        db 131  ; Volume + possible Pitch up/down.
        db 127, 73      ; Escaped note: 73.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 110  ; Note: 70.
        db 131  ; Volume + possible Pitch up/down.
        db 110  ; Note: 70.
        db 129  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 89   ; Note: 49.
        db 130  ; Volume + possible Pitch up/down.
        db 89   ; Note: 49.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 101  ; Note: 61.
        db 130  ; Volume + possible Pitch up/down.
        db 101  ; Note: 61.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 104  ; Note: 64.
        db 130  ; Volume + possible Pitch up/down.
        db 104  ; Note: 64.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 111  ; Note: 71.
        db 130  ; Volume + possible Pitch up/down.
        db 111  ; Note: 71.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 110  ; Note: 70.
        db 130  ; Volume + possible Pitch up/down.
        db 110  ; Note: 70.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 106  ; Note: 66.
        db 130  ; Volume + possible Pitch up/down.
        db 106  ; Note: 66.
        db 128  ; Volume + possible Pitch up/down.
        db 61, 6        ; Long wait: 7.


Untitled_Subsong1_Track54
        db 255, 23      ; Escaped note: 23.
        db 16   ; New instrument: 8.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 11   ; Note: 35.
        db 62   ; Short wait: 1.

        db 63, 21       ; Escaped note: 21.
        db 63, 19       ; Escaped note: 19.
        db 63, 17       ; Escaped note: 17.
        db 62   ; Short wait: 1.

        db 5    ; Note: 29.
        db 62   ; Short wait: 1.

        db 63, 19       ; Escaped note: 19.
        db 63, 21       ; Escaped note: 21.
        db 63, 23       ; Escaped note: 23.
        db 75   ; Note: 35.
        db 129  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 130  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 73   ; Note: 33.
        db 128  ; Volume + possible Pitch up/down.
        db 7    ; Note: 31.
        db 5    ; Note: 29.
        db 62   ; Short wait: 1.

        db 127, 77      ; Escaped note: 77.
        db 132  ; Volume + possible Pitch up/down.
        db 63, 76       ; Escaped note: 76.
        db 63, 72       ; Escaped note: 72.
        db 45   ; Note: 69.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track55
        db 227  ; Note: 59.
        db 36   ; New instrument: 18.
        db 130  ; Volume + possible Pitch up/down.
        db 38   ; Note: 62.
        db 43   ; Note: 67.
        db 45   ; Note: 69.
        db 47   ; Note: 71.
        db 63, 74       ; Escaped note: 74.
        db 63, 72       ; Escaped note: 72.
        db 45   ; Note: 69.
        db 41   ; Note: 65.
        db 36   ; Note: 60.
        db 33   ; Note: 57.
        db 29   ; Note: 53.
        db 26   ; Note: 50.
        db 35   ; Note: 59.
        db 38   ; Note: 62.
        db 43   ; Note: 67.
        db 47   ; Note: 71.
        db 63, 74       ; Escaped note: 74.
        db 63, 72       ; Escaped note: 72.
        db 100  ; Note: 60.
        db 133  ; Volume + possible Pitch up/down.
        db 109  ; Note: 69.
        db 130  ; Volume + possible Pitch up/down.
        db 97   ; Note: 57.
        db 133  ; Volume + possible Pitch up/down.
        db 105  ; Note: 65.
        db 130  ; Volume + possible Pitch up/down.
        db 93   ; Note: 53.
        db 133  ; Volume + possible Pitch up/down.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track56
        db 255, 23      ; Escaped note: 23.
        db 16   ; New instrument: 8.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 63, 21       ; Escaped note: 21.
        db 63, 19       ; Escaped note: 19.
        db 63, 17       ; Escaped note: 17.
        db 62   ; Short wait: 1.

        db 63, 17       ; Escaped note: 17.
        db 63, 17       ; Escaped note: 17.
        db 63, 19       ; Escaped note: 19.
        db 63, 21       ; Escaped note: 21.
        db 63, 23       ; Escaped note: 23.
        db 62   ; Short wait: 1.

        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 63, 21       ; Escaped note: 21.
        db 63, 19       ; Escaped note: 19.
        db 63, 17       ; Escaped note: 17.
        db 60   ; No note, effects only.
        db 143  ; Volume + possible Pitch up/down.
        db 127, 77      ; Escaped note: 77.
        db 132  ; Volume + possible Pitch up/down.
        db 63, 76       ; Escaped note: 76.
        db 63, 72       ; Escaped note: 72.
        db 63, 74       ; Escaped note: 74.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track57
        db 255, 23      ; Escaped note: 23.
        db 12   ; New instrument: 6.
        db 128  ; Volume + possible Pitch up/down.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 63, 21       ; Escaped note: 21.
        db 63, 19       ; Escaped note: 19.
        db 63, 17       ; Escaped note: 17.
        db 63, 17       ; Escaped note: 17.
        db 63, 17       ; Escaped note: 17.
        db 63, 17       ; Escaped note: 17.
        db 63, 19       ; Escaped note: 19.
        db 63, 21       ; Escaped note: 21.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 63, 23       ; Escaped note: 23.
        db 63, 21       ; Escaped note: 21.
        db 63, 19       ; Escaped note: 19.
        db 63, 17       ; Escaped note: 17.
        db 60   ; No note, effects only.
        db 143  ; Volume + possible Pitch up/down.
        db 127, 81      ; Escaped note: 81.
        db 132  ; Volume + possible Pitch up/down.
        db 63, 79       ; Escaped note: 79.
        db 63, 76       ; Escaped note: 76.
        db 63, 77       ; Escaped note: 77.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track58
        db 255, 23      ; Escaped note: 23.
        db 16   ; New instrument: 8.
        db 128  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 11   ; Note: 35.
        db 62   ; Short wait: 1.

        db 63, 21       ; Escaped note: 21.
        db 63, 19       ; Escaped note: 19.
        db 63, 17       ; Escaped note: 17.
        db 62   ; Short wait: 1.

        db 5    ; Note: 29.
        db 62   ; Short wait: 1.

        db 63, 19       ; Escaped note: 19.
        db 63, 21       ; Escaped note: 21.
        db 63, 23       ; Escaped note: 23.
        db 75   ; Note: 35.
        db 129  ; Volume + possible Pitch up/down.
        db 60   ; No note, effects only.
        db 130  ; Volume + possible Pitch up/down.
        db 62   ; Short wait: 1.

        db 73   ; Note: 33.
        db 128  ; Volume + possible Pitch up/down.
        db 7    ; Note: 31.
        db 5    ; Note: 29.
        db 127, 77      ; Escaped note: 77.
        db 132  ; Volume + possible Pitch up/down.
        db 63, 77       ; Escaped note: 77.
        db 63, 79       ; Escaped note: 79.
        db 63, 77       ; Escaped note: 77.
        db 63, 81       ; Escaped note: 81.
        db 61, 23       ; Long wait: 24.


Untitled_Subsong1_Track60
        db 255, 79      ; Escaped note: 79.
        db 16   ; New instrument: 8.
        db 132  ; Volume + possible Pitch up/down.
        db 63, 79       ; Escaped note: 79.
        db 63, 81       ; Escaped note: 81.
        db 63, 79       ; Escaped note: 79.
        db 63, 83       ; Escaped note: 83.
        db 61, 42       ; Long wait: 43.


Untitled_Subsong1_Track61
        db 239  ; Note: 71.
        db 16   ; New instrument: 8.
        db 132  ; Volume + possible Pitch up/down.
        db 47   ; Note: 71.
        db 63, 72       ; Escaped note: 72.
        db 47   ; Note: 71.
        db 63, 74       ; Escaped note: 74.
        db 61, 42       ; Long wait: 43.


