; Sound Effects for song Sound effects from Dead on TIme, version 1.0, generated by Arkos Tracker 2.

; The sound effects, starting at 1.
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect1      ; Sound effect 1
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect2      ; Sound effect 2
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect3      ; Sound effect 3
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect4      ; Sound effect 4
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect5      ; Sound effect 5
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect6      ; Sound effect 6
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect7      ; Sound effect 7
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect8      ; Sound effect 8
        dw 0    ; Sound effect 9
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect10     ; Sound effect 10
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect11     ; Sound effect 11
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect12     ; Sound effect 12
        dw SoundeffectsfromDeadonTIme_Subsong_SoundEffect13     ; Sound effect 13

; Sound effect 1.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect1
SoundeffectsfromDeadonTIme_Subsong_SoundEffect1_Loop    db 189  ; Soft only. Volume: 15.
        db 1    ; Noise: 1.
        dw 119  ; Software period.

        db 177  ; Soft only. Volume: 12.
        db 1    ; Noise: 1.
        dw 126  ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 2.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect2
SoundeffectsfromDeadonTIme_Subsong_SoundEffect2_Loop    db 189  ; Soft only. Volume: 15.
        db 1    ; Noise: 1.
        dw 1911 ; Software period.

        db 189  ; Soft only. Volume: 15.
        db 8    ; Noise: 8.
        dw 2025 ; Software period.

        db 185  ; Soft only. Volume: 14.
        db 2    ; Noise: 2.
        dw 2551 ; Software period.

        db 181  ; Soft only. Volume: 13.
        db 16   ; Noise: 16.
        dw 1351 ; Software period.

        db 177  ; Soft only. Volume: 12.
        db 2    ; Noise: 2.
        dw 1432 ; Software period.

        db 173  ; Soft only. Volume: 11.
        db 2    ; Noise: 2.
        dw 1517 ; Software period.

        db 165  ; Soft only. Volume: 9.
        db 16   ; Noise: 16.
        dw 2273 ; Software period.

        db 157  ; Soft only. Volume: 7.
        db 31   ; Noise: 31.
        dw 758  ; Software period.

        db 153  ; Soft only. Volume: 6.
        db 7    ; Noise: 7.
        dw 506  ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 3.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect3
SoundeffectsfromDeadonTIme_Subsong_SoundEffect3_Loop    db 189  ; Soft only. Volume: 15.
        db 5    ; Noise: 5.
        dw 30   ; Software period.

        db 189  ; Soft only. Volume: 15.
        db 1    ; Noise: 1.
        dw 60   ; Software period.

        db 57   ; Soft only. Volume: 14.
        dw 40   ; Software period.

        db 53   ; Soft only. Volume: 13.
        dw 60   ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 4.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect4
SoundeffectsfromDeadonTIme_Subsong_SoundEffect4_Loop    db 189  ; Soft only. Volume: 15.
        db 1    ; Noise: 1.
        dw 119  ; Software period.

        db 57   ; Soft only. Volume: 14.
        dw 60   ; Software period.

        db 181  ; Soft only. Volume: 13.
        db 1    ; Noise: 1.
        dw 95   ; Software period.

        db 49   ; Soft only. Volume: 12.
        dw 47   ; Software period.

        db 185  ; Soft only. Volume: 14.
        db 1    ; Noise: 1.
        dw 80   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 40   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 15   ; Hardware period.
        dw 478  ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 239  ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 15   ; Hardware period.
        dw 478  ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 239  ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 15   ; Hardware period.
        dw 478  ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 239  ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 30   ; Hardware period.
        dw 956  ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 239  ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 30   ; Hardware period.
        dw 956  ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 239  ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 5.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect5
SoundeffectsfromDeadonTIme_Subsong_SoundEffect5_Loop    db 189  ; Soft only. Volume: 15.
        db 1    ; Noise: 1.
        dw 30   ; Software period.

        db 181  ; Soft only. Volume: 13.
        db 31   ; Noise: 31.
        dw 60   ; Software period.

        db 185  ; Soft only. Volume: 14.
        db 1    ; Noise: 1.
        dw 45   ; Software period.

        db 157  ; Soft only. Volume: 7.
        db 15   ; Noise: 15.
        dw 60   ; Software period.

        db 181  ; Soft only. Volume: 13.
        db 1    ; Noise: 1.
        dw 60   ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 6.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect6
SoundeffectsfromDeadonTIme_Subsong_SoundEffect6_Loop    db 189  ; Soft only. Volume: 15.
        db 8    ; Noise: 8.
        dw 60   ; Software period.

        db 169  ; Soft only. Volume: 10.
        db 1    ; Noise: 1.
        dw 106  ; Software period.

        db 53   ; Soft only. Volume: 13.
        dw 142  ; Software period.

        db 177  ; Soft only. Volume: 12.
        db 1    ; Noise: 1.
        dw 159  ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 7.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect7
SoundeffectsfromDeadonTIme_Subsong_SoundEffect7_Loop    db 189  ; Soft only. Volume: 15.
        db 6    ; Noise: 6.
        dw 169  ; Software period.

        db 189  ; Soft only. Volume: 15.
        db 1    ; Noise: 1.
        dw 60   ; Software period.

        db 189  ; Soft only. Volume: 15.
        db 2    ; Noise: 2.
        dw 60   ; Software period.

        db 189  ; Soft only. Volume: 15.
        db 1    ; Noise: 1.
        dw 60   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 84   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 2    ; Hardware period.
        dw 30   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 60   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 2    ; Hardware period.
        dw 30   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 60   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 2    ; Hardware period.
        dw 30   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 60   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 2    ; Hardware period.
        dw 30   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 60   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 2    ; Hardware period.
        dw 30   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 60   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 2    ; Hardware period.
        dw 30   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 60   ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 8.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect8
SoundeffectsfromDeadonTIme_Subsong_SoundEffect8_Loop    db 189  ; Soft only. Volume: 15.
        db 1    ; Noise: 1.
        dw 60   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 28   ; Software period.

        db 189  ; Soft only. Volume: 15.
        db 1    ; Noise: 1.
        dw 53   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 27   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 50   ; Software period.

        db 61   ; Soft only. Volume: 15.
        dw 25   ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 10.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect10
SoundeffectsfromDeadonTIme_Subsong_SoundEffect10_Loop   db 19   ; Soft and Hard. Env: 10.
        dw 30   ; Hardware period.
        dw 119  ; Software period.

        db 19   ; Soft and Hard. Env: 10.
        dw 7    ; Hardware period.
        dw 116  ; Software period.

        db 19   ; Soft and Hard. Env: 10.
        dw 28   ; Hardware period.
        dw 112  ; Software period.

        db 19   ; Soft and Hard. Env: 10.
        dw 7    ; Hardware period.
        dw 110  ; Software period.

        db 19   ; Soft and Hard. Env: 10.
        dw 27   ; Hardware period.
        dw 108  ; Software period.

        db 19   ; Soft and Hard. Env: 10.
        dw 7    ; Hardware period.
        dw 106  ; Software period.

        db 19   ; Soft and Hard. Env: 10.
        dw 26   ; Hardware period.
        dw 103  ; Software period.

        db 19   ; Soft and Hard. Env: 10.
        dw 6    ; Hardware period.
        dw 100  ; Software period.

        db 19   ; Soft and Hard. Env: 10.
        dw 24   ; Hardware period.
        dw 96   ; Software period.

        db 19   ; Soft and Hard. Env: 10.
        dw 6    ; Hardware period.
        dw 94   ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 11.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect11
SoundeffectsfromDeadonTIme_Subsong_SoundEffect11_Loop   db 3    ; Soft and Hard. Env: 8.
        dw 1    ; Hardware period.
        dw 13   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 2    ; Hardware period.
        dw 24   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 1    ; Hardware period.
        dw 15   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 2    ; Hardware period.
        dw 38   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 2    ; Hardware period.
        dw 24   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 4    ; Hardware period.
        dw 60   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 2    ; Hardware period.
        dw 38   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 6    ; Hardware period.
        dw 95   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 4    ; Hardware period.
        dw 60   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 9    ; Hardware period.
        dw 150  ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 6    ; Hardware period.
        dw 95   ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 17   ; Hardware period.
        dw 268  ; Software period.

        db 3    ; Soft and Hard. Env: 8.
        dw 25   ; Hardware period.
        dw 402  ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 12.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect12
SoundeffectsfromDeadonTIme_Subsong_SoundEffect12_Loop   db 189  ; Soft only. Volume: 15.
        db 1    ; Noise: 1.
        dw 119  ; Software period.

        db 53   ; Soft only. Volume: 13.
        dw 133  ; Software period.

        db 49   ; Soft only. Volume: 12.
        dw 146  ; Software period.

        db 4    ; End of the sound effect.

; Sound effect 13.
SoundeffectsfromDeadonTIme_Subsong_SoundEffect13
SoundeffectsfromDeadonTIme_Subsong_SoundEffect13_Loop   db 200  ; No soft, no hard. Volume: 9.
        db 27   ; Noise: 27.

        db 216  ; No soft, no hard. Volume: 11.
        db 5    ; Noise: 5.

        db 248  ; No soft, no hard. Volume: 15.
        db 8    ; Noise: 8.

        db 232  ; No soft, no hard. Volume: 13.
        db 16   ; Noise: 16.

        db 216  ; No soft, no hard. Volume: 11.
        db 5    ; Noise: 5.

        db 4    ; End of the sound effect.

