; Song Untitled, in AKY version 1.0, generated by Arkos Tracker 2.

Main_Subsong0:

; Header
	dc.b 0	; Format version: 0 and endianness: big-endian.
	dc.b 3	; How many channels are encoded.
; Frequency of the PSG index 0: 1000000Hz.
	dc.b 0, 15, 66, 64

Main_Subsong0_Linker:
; Pattern 0
Main_Subsong0_LinkerLoop:	; Loops here.
	dc.w 384	; Duration in frames.
	dc.w Main_Subsong0_Track_0-Main_Subsong0
	dc.w Main_Subsong0_Track_2-Main_Subsong0
	dc.w Main_Subsong0_Track_2-Main_Subsong0

	dc.w 0	; Loops (duration = 0).
	dc.w Main_Subsong0_LinkerLoop-Main_Subsong0

; The tracks.
Main_Subsong0_Track_0:
	dc.b 255	; Duration.
	dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0

	dc.b 129	; Duration.
	dc.w Main_Subsong0_RegisterBlock_1-Main_Subsong0

Main_Subsong0_Track_2:
	dc.b 255	; Duration.
	dc.w Main_Subsong0_RegisterBlock_3-Main_Subsong0

	dc.b 129	; Duration.
	dc.w Main_Subsong0_RegisterBlock_3-Main_Subsong0


; The RegisterBlocks.
Main_Subsong0_RegisterBlock_0:
	dc.b 131	; Initial State : software and hardware.
	dc.b 1, 222	; Software period.
	dc.b 0, 60	; Hardware period.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 3	; Non-initial State, software and hardware.

Main_Subsong0_RegisterBlock_0_Loop:
	dc.b 3	; Non-initial State, software and hardware.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 55	; Non-initial State, software and hardware.
	dc.b 30	; Hardware period, LSB.
	dc.b 239	; Software period, LSB.
	dc.b 0	; Software period, MSB.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 55	; Non-initial State, software and hardware.
	dc.b 60	; Hardware period, LSB.
	dc.b 222	; Software period, LSB.
	dc.b 1	; Software period, MSB.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 3	; Non-initial State, software and hardware.

	dc.b 8	; Loop to index 3.
	dc.w Main_Subsong0_RegisterBlock_0_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_3:
	dc.b 0	; Initial State: no software, no hardware.

Main_Subsong0_RegisterBlock_3_Loop:
	dc.b 4	; Non-initial State, no software no hardware.

	dc.b 8	; Loop to index 1.
	dc.w Main_Subsong0_RegisterBlock_3_Loop-Main_Subsong0


Main_Subsong0_RegisterBlock_1:
	dc.b 131	; Initial State : software and hardware.
	dc.b 1, 222	; Software period.
	dc.b 0, 60	; Hardware period.

	dc.b 8 
    dc.w Main_Subsong0_RegisterBlock_0-Main_Subsong0 + 8	; Optimization: goto common Block at index 4.

